// @ts-nocheck
/**
 * Element Static Imports
 *
 * AUTO-GENERATED by scripts/generate-element-imports.ts - DO NOT EDIT MANUALLY
 *
 * This file registers all available PIE elements using package specifiers.
 * We intentionally avoid absolute filesystem paths to keep local-machine
 * details out of generated files and build artifacts.
 *
 * IMPORTANT: import specifiers are static strings so Vite can analyze
 * and optimize them without leaking machine-specific absolute paths.
 *
 * The workspace resolver plugin handles resolving dependencies that the
 * element dist files import (like @pie-element/shared-math-rendering-katex)
 *
 * Generated at build-time by prebuild script
 */

// Element module registry
const elementModules = new Map();
const controllerModules = new Map();
const authorModules = new Map();
const printModules = new Map();

// Register helper functions
export function registerElement(name, importer) {
  elementModules.set(name, importer);
}

export function registerController(name, importer) {
  controllerModules.set(name, importer);
}

export function registerAuthor(name, importer) {
  authorModules.set(name, importer);
}

export function registerPrint(name, importer) {
  printModules.set(name, importer);
}

// Get helper functions
export function getElementModule(name) {
  return elementModules.get(name);
}

export function getControllerModule(name) {
  return controllerModules.get(name);
}

export function getAuthorModule(name) {
  return authorModules.get(name);
}

export function getPrintModule(name) {
  return printModules.get(name);
}

export function hasElementModule(name) {
  return elementModules.has(name);
}

// ============================================================================
// ELEMENT REGISTRATIONS
// ============================================================================

// Register element: mc-populated-blank
registerElement('mc-populated-blank', () => import('@pie-element/mc-populated-blank/delivery'));
registerController('mc-populated-blank', () => import('@pie-element/mc-populated-blank/controller'));
registerAuthor('mc-populated-blank', () => import('@pie-element/mc-populated-blank/author'));
registerPrint('mc-populated-blank', () => import('@pie-element/mc-populated-blank/print'));
