export default {
  translation: {
    categorize: {
      limitMaxChoicesPerCategory:
        "You've reached the limit of {{maxChoicesPerCategory}} responses per area. To add another response, one must first be removed.",
      maxChoicesPerCategoryRestriction:
        'To change this value to {{maxChoicesPerCategory}}, each category must have {{maxChoicesPerCategory}} or fewer answer choice[s].',
    },
    dragInTheBlank: {
      blank: 'Blank {{index}}',
    },
    ebsr: {
      part: 'Part {{index}}',
      twoPartQuestion: 'Two-Part Question',
    },
    editableHtml: {
      responseAreaToolbar: 'Response area',
      toolbar: 'Editing tools',
      buttons: {
        insertTable: 'Insert table',
        addTableRow: 'Add table row',
        removeTableRow: 'Remove table row',
        addTableColumn: 'Add table column',
        removeTableColumn: 'Remove table column',
        removeTable: 'Remove table',
        tableBorders: 'Table borders',
        bold: 'Bold',
        italic: 'Italic',
        strikethrough: 'Strikethrough',
        code: 'Code',
        underline: 'Underline',
        subscript: 'Subscript',
        superscript: 'Superscript',
        insertImage: 'Insert image',
        insertVideo: 'Insert video',
        insertAudio: 'Insert audio',
        cssClasses: 'CSS classes',
        blockquote: 'Blockquote',
        heading: 'Heading',
        insertMath: 'Insert math',
        spanishCharacters: 'Spanish characters (ñ)',
        specialCharacters: 'Special characters (€)',
        textAlignment: 'Text alignment',
        bulletedList: 'Bulleted list',
        numberedList: 'Numbered list',
        done: 'Done',
      },
    },
    explicitConstructedResponse: {
      fillInTheBlankQuestion: 'Fill in the Blank Question',
      response: 'Response {{index}} of {{total}}',
    },
    extendedTextEntry: {
      comment: 'Comment',
      constructedResponseQuestion: 'Constructed Response Question',
      response: 'Your response',
      writtenResponseQuestion: 'Written Response Question',
    },
    fractionModel: {
      modelLabel_one: 'Model {{index}} of {{total}}: {{selected}} of {{count}} part selected',
      modelLabel_other: 'Model {{index}} of {{total}}: {{selected}} of {{count}} parts selected',
    },
    numberLine: {
      addElementLimit_one: 'You can only add {{count}} element',
      addElementLimit_other: 'You can only add {{count}} elements',
      clearAll: 'Clear all',
      closedEnd: 'closed',
      elementCorrect: 'Correct.',
      elementIncorrect: 'Incorrect.',
      graphLabel: 'Number line from {{min}} to {{max}}, with a tick every {{interval}}',
      line: 'Line from {{left}} ({{leftEnd}}) to {{right}} ({{rightEnd}}).',
      openEnd: 'open',
      plottedNone: 'Nothing is plotted.',
      pointClosed: 'Closed point at {{position}}.',
      pointOpen: 'Open point at {{position}}.',
      rayLeft: 'Ray from {{position}} ({{end}}) to the left.',
      rayRight: 'Ray from {{position}} ({{end}}) to the right.',
    },
    hotspot: {
      correctlySelected: 'Correctly selected',
      image_one: 'Image with {{count}} hotspot',
      image_other: 'Image with {{count}} hotspots',
      shape: 'Hotspot {{index}} of {{total}}',
      shouldHaveBeenSelected: 'Should have been selected',
      shouldNotHaveBeenSelected: 'Should not have been selected',
    },
    imageClozeAssociation: {
      answerChoice: 'Answer choice {{index}} of {{total}}',
      image_one: 'Image with {{count}} response area',
      image_other: 'Image with {{count}} response areas',
      reachedLimit_one:
        'You’ve reached the limit of {{count}} response per area. To add another response, one must first be removed.',
      reachedLimit_other: 'Full',
      responseArea: 'Response area {{index}} of {{total}}',
    },
    inlineDropdown: {
      inlineDropdownQuestion: 'Inline Dropdown Question',
      query: 'Query',
      queryNumber: 'Query {{index}}',
      showRationaleForChoices: 'Show Rationale for choices',
      hideRationaleForChoices: 'Hide Rationale for choices',
    },
    drawingResponse: {
      fillColor: 'Fill color',
      outlineColor: 'Outline color',
      noFill: 'No fill',
      lightblue: 'Light blue',
      lightyellow: 'Light yellow',
      red: 'Red',
      orange: 'Orange',
      yellow: 'Yellow',
      violet: 'Violet',
      blue: 'Blue',
      green: 'Green',
      white: 'White',
      black: 'Black',
      onDoubleClick: 'Double click to edit this text. Press Enter to submit.',
      drawingArea: 'Drawing area',
      drawingAreaOverImage: 'Drawing area over a background image',
      tools: {
        select: 'Select',
        freeDraw: 'Free Draw',
        line: 'Line',
        rectangle: 'Rectangle',
        circle: 'Circle',
        textEntry: 'Text Entry',
        eraser: 'Eraser',
      },
    },
    charting: {
      addCategory: 'Add category',
      actions: 'Actions',
      add: 'Add',
      delete: 'Delete',
      newLabel: 'New label',
      categoryLabel: 'Category {{index}} label',
      categoryLabelValue: 'Category {{index}} label: {{label}}',
      category: 'Category {{index}}',
      reachedLimit_other: "There can't be more than {{count}} categories.",
      keyLegend: {
        incorrectAnswer: 'Student incorrect answer',
        correctAnswer: 'Student correct answer',
        correctKeyAnswer: 'Answer key correct',
      },
      chartTypes: {
        bar: 'Bar chart',
        histogram: 'Histogram',
        lineDot: 'Line chart with dots',
        lineCross: 'Line chart with crosses',
        dotPlot: 'Dot plot',
        linePlot: 'Line plot',
      },
      categories_zero: 'No categories.',
      categories_one: '{{count}} category: {{categories}}.',
      categories_other: '{{count}} categories: {{categories}}.',
      valueRange: 'Values from {{min}} to {{max}}.',
      labelledValueRange: '{{label}} from {{min}} to {{max}}.',
    },
    graphing: {
      graph: 'Coordinate graph',
      axisRange: '{{axis}} axis from {{min}} to {{max}}.',
      plotted_zero: 'Nothing plotted.',
      plotted_one: '{{count}} object plotted: {{marks}}.',
      plotted_other: '{{count}} objects plotted: {{marks}}.',
      shadedRegion: 'Shaded region',
      point: 'Point',
      circle: 'Circle',
      line: 'Line',
      parabola: 'Parabola',
      absolute: 'Absolute Value',
      exponential: 'Exponential',
      polygon: 'Polygon',
      ray: 'Ray',
      segment: 'Segment',
      sine: 'Sine',
      vector: 'Vector',
      label: 'Label',
      markLabel: 'Label at ({{x}}, {{y}})',
      correctMarkLabel: 'Correct label at ({{x}}, {{y}})',
      redo: 'Redo',
      reset: 'Reset',
      keyLegend: {
        missingRequiredLabel: 'Missing Required Label',
        answerKeyCorrect: 'Answer Key Correct',
        answerKeyCorrectLabel: 'Answer Key Correct Label',
        studentIncorrect: 'Student Incorrect',
        incorrectStudentLabel: 'Incorrect Student Label',
        studentCorrect: 'Student Correct',
        studentCorrectLabel: 'Student Correct Label',
      },
    },
    mathInline: {
      keypadInstructions:
        'This field supports both keypad and keyboard input. Use the keyboard to access and interact with the on-screen math keypad, which accepts LaTeX markup. Use the down arrow key to open the keypad and navigate its buttons. Use the escape key to close the keypad and return to the input field.',
      mathEquationResponseQuestion: 'Math Equation Response Question',
      mathResponseQuestion: 'Math Response Question',
      primaryCorrectWithAlternates:
        'Note: The answer shown above is the primary correct answer specified by the author for this item, but other answers may also be recognized as correct.',
    },
    mathInput: {
      enterAnswer: 'Enter answer',
    },
    mcPopulatedBlank: {
      answerChoices: 'Answer choices',
      blankLabel: 'blank',
      emptyBlank: '(blank)',
      blankPreSelectionHint: 'The answer you choose will appear on the blank line above.',
      correctAnswerSelected: 'Correct answer selected',
      incorrectAnswerSelected: 'Incorrect answer selected',
      selectedAnswerImage: 'Selected answer image',
      choiceImage: 'Choice {{id}}',
      clickToEnableAutoplay: 'Click to enable audio autoplay',
      audioResourceUnavailable: 'Audio is enabled but no playable audio URL is configured.',
      listen: 'Listen',
      listenSilentAlt: 'Repeat instructions',
      listenPlayingAlt: 'Instructions are playing',
      printAudio: 'Audio:',
      printTranscript: 'Transcript:',
    },
    multipleChoice: {
      minSelections: 'Select at least {{minSelections}}.',
      maxSelections_one: 'Only {{maxSelections}} answer is allowed.',
      maxSelections_other: 'Only {{maxSelections}} answers are allowed.',
      minmaxSelections_equal: 'Select {{minSelections}}.',
      minmaxSelections_range: 'Select between {{minSelections}} and {{maxSelections}}.',
      multipleChoiceQuestion: 'Multiple Choice Question',
      multipleCorrectAnswerQuestion: 'Multiple Correct Answer Question',
      multipleSelectQuestion: 'Multiple Select Question',
    },
    rubric: {
      rubric: 'Rubric',
      showRubric: 'Show Rubric',
      hideRubric: 'Hide Rubric',
    },
    selectText: {
      correctAnswerSelected: 'Correct',
      correctAnswerNotSelected: 'Correct Answer Not Selected',
      incorrectSelection: 'Incorrect Selection',
      key: 'Key',
      textGroup: 'Selectable text',
      textGroupWithLimit: 'Selectable text, select up to {{max}}',
      tokenPosition: '{{index}} of {{total}}',
    },
    simpleCloze: {
      correctAnswerShown: 'Correct answer',
      correct: 'Correct',
      incorrect: 'Incorrect',
      unanswered: 'No answer',
      placeholder: 'Enter your answer...',
      answerInput: 'Your answer',
      printCorrectAnswer: 'Correct answer:',
      printAnswerBlank: 'Answer blank',
    },
    vennClassification: {
      tray: 'Tiles to classify',
      unknownTarget: 'unknown',
      cancelled: 'Cancelled',
      returnedToTray: '{{name}} returned to tray',
      placedIn: '{{name}} placed in {{target}}',
      pickedUp: 'Picked up {{name}}',
      pickedUpWithKeyboard:
        'Picked up {{name}}, drop target: {{target}}. Use arrow keys to choose a drop target, Enter to drop, Escape to cancel.',
      dropTarget: 'Drop target: {{target}}',
      unsupportedCircles_one:
        'This diagram cannot be shown: it has {{count}} circle, and only {{supported}} are supported.',
      unsupportedCircles_other:
        'This diagram cannot be shown: it has {{count}} circles, and only {{supported}} are supported.',
      setNumber: 'Set {{number}}',
      regionOnly: '{{set}} only',
      regionNeither: 'Neither {{first}} nor {{second}}',
      regionNoneOf: 'None of {{sets}}',
      regionAndSeparator: ' and ',
      tileFallbackName: 'Tile',
      tileNotPlaced: 'not placed',
      tileInRegion: 'in {{region}}',
      tileCorrect: 'correct',
      tileIncorrect: 'incorrect',
    },
  },
  common: {
    undo: 'Undo',
    clearAll: 'Clear all',
    correct: 'Correct',
    incorrect: 'Incorrect',
    showCorrectAnswer: 'Show correct answer',
    hideCorrectAnswer: 'Hide correct answer',
    showTeacherInstructions: 'Show Teacher Instructions',
    hideTeacherInstructions: 'Hide Teacher Instructions',
    show: 'Show',
    hide: 'Hide',
    showRationale: 'Show Rationale',
    hideRationale: 'Hide Rationale',
    commonCorrectAnswerWithAlternates:
      'Note: The answer shown above is the most common correct answer for this item. One or more additional correct answers are also defined, and will also be recognized as correct.',
    warning: 'Warning',
    showNote: 'Show Note',
    hideNote: 'Hide Note',
    cancel: 'Cancel',
    playAudio: 'Play audio',
  },
};
