export default {
  translation: {
    categorize: {
      limitMaxChoicesPerCategory:
        "You've reached the limit of {{maxChoicesPerCategory}} responses per area. To add another response, one must first be removed.",
      maxChoicesPerCategoryRestriction:
        'To change this value to {{maxChoicesPerCategory}}, each category must have {{maxChoicesPerCategory}} or fewer answer choice[s].',
    },
    ebsr: {
      part: 'Part {{index}}',
    },
    numberLine: {
      addElementLimit_one: 'You can only add {{count}} element',
      addElementLimit_other: 'You can only add {{count}} elements',
      clearAll: 'Clear all',
    },
    imageClozeAssociation: {
      reachedLimit_one:
        'You’ve reached the limit of {{count}} response per area. To add another response, one must first be removed.',
      reachedLimit_other: 'Full',
    },
    drawingResponse: {
      fillColor: 'Fill color',
      outlineColor: 'Outline color',
      noFill: 'No fill',
      lightblue: 'Light blue',
      lightyellow: 'Light yellow',
      red: 'Red',
      orange: 'Orange',
      yellow: 'Yellow',
      violet: 'Violet',
      blue: 'Blue',
      green: 'Green',
      white: 'White',
      black: 'Black',
      onDoubleClick: 'Double click to edit this text. Press Enter to submit.',
    },
    charting: {
      addCategory: 'Add category',
      actions: 'Actions',
      add: 'Add',
      delete: 'Delete',
      newLabel: 'New label',
      reachedLimit_other: "There can't be more than {{count}} categories.",
      keyLegend: {
        incorrectAnswer: 'Student incorrect answer',
        correctAnswer: 'Student correct answer',
        correctKeyAnswer: 'Answer key correct',
      },
    },
    graphing: {
      point: 'Point',
      circle: 'Circle',
      line: 'Line',
      parabola: 'Parabola',
      absolute: 'Absolute Value',
      exponential: 'Exponential',
      polygon: 'Polygon',
      ray: 'Ray',
      segment: 'Segment',
      sine: 'Sine',
      vector: 'Vector',
      label: 'Label',
      redo: 'Redo',
      reset: 'Reset',
    },
    mathInline: {
      primaryCorrectWithAlternates:
        'Note: The answer shown above is the primary correct answer specified by the author for this item, but other answers may also be recognized as correct.',
    },
    mcPopulatedBlank: {
      answerChoices: 'Answer choices',
      blankLabel: 'blank',
      emptyBlank: '(blank)',
      blankPreSelectionHint: 'The answer you choose will appear on the blank line above.',
      correctAnswerSelected: 'Correct answer selected',
      incorrectAnswerSelected: 'Incorrect answer selected',
      selectedAnswerImage: 'Selected answer image',
      choiceImage: 'Choice {{id}}',
      clickToEnableAutoplay: 'Click to enable audio autoplay',
      audioResourceUnavailable: 'Audio is enabled but no playable audio URL is configured.',
      listen: 'Listen',
      listenSilentAlt: 'Repeat instructions',
      listenPlayingAlt: 'Instructions are playing',
    },
    multipleChoice: {
      minSelections: 'Select at least {{minSelections}}.',
      maxSelections_one: 'Only {{maxSelections}} answer is allowed.',
      maxSelections_other: 'Only {{maxSelections}} answers are allowed.',
      minmaxSelections_equal: 'Select {{minSelections}}.',
      minmaxSelections_range: 'Select between {{minSelections}} and {{maxSelections}}.',
    },
    selectText: {
      correctAnswerSelected: 'Correct',
      correctAnswerNotSelected: 'Correct Answer Not Selected',
      incorrectSelection: 'Incorrect Selection',
      key: 'Key',
    },
    simpleCloze: {
      correctAnswerShown: 'Correct answer',
      correct: 'Correct',
      incorrect: 'Incorrect',
      placeholder: 'Enter your answer...',
      answerInput: 'Your answer',
      printCorrectAnswer: 'Correct answer:',
      printAnswerBlank: 'Answer blank',
    },
    vennClassification: {
      tray: 'Tiles to classify',
      unknownTarget: 'unknown',
      cancelled: 'Cancelled',
      returnedToTray: '{{name}} returned to tray',
      placedIn: '{{name}} placed in {{target}}',
      pickedUp: 'Picked up {{name}}',
      pickedUpWithKeyboard:
        'Picked up {{name}}, drop target: {{target}}. Use arrow keys to choose a drop target, Enter to drop, Escape to cancel.',
      dropTarget: 'Drop target: {{target}}',
      unsupportedCircles_one:
        'This diagram cannot be shown: it has {{count}} circle, and only {{supported}} are supported.',
      unsupportedCircles_other:
        'This diagram cannot be shown: it has {{count}} circles, and only {{supported}} are supported.',
      setNumber: 'Set {{number}}',
      regionOnly: '{{set}} only',
      regionNeither: 'Neither {{first}} nor {{second}}',
      regionNoneOf: 'None of {{sets}}',
      regionAndSeparator: ' and ',
      tileFallbackName: 'Tile',
      tileNotPlaced: 'not placed',
      tileInRegion: 'in {{region}}',
      tileCorrect: 'correct',
      tileIncorrect: 'incorrect',
    },
  },
  common: {
    undo: 'Undo',
    clearAll: 'Clear all',
    correct: 'Correct',
    incorrect: 'Incorrect',
    showCorrectAnswer: 'Show correct answer',
    hideCorrectAnswer: 'Hide correct answer',
    commonCorrectAnswerWithAlternates:
      'Note: The answer shown above is the most common correct answer for this item. One or more additional correct answers are also defined, and will also be recognized as correct.',
    warning: 'Warning',
    showNote: 'Show Note',
    hideNote: 'Hide Note',
    cancel: 'Cancel',
  },
};
