export default {
  translation: {
    categorize: {
      limitMaxChoicesPerCategory:
        'Has alcanzado el límite de {{maxChoicesPerCategory}} respuestas por área. Para agregar otra respuesta, primero se debe eliminar una respuesta.',
      maxChoicesPerCategoryRestriction:
        'Para cambiar este valor a {{maxChoicesPerCategory}}, cada categoría debe tener {{maxChoicesPerCategory}} o menos opciones de respuesta',
    },
    dragInTheBlank: {
      blank: 'Espacio en blanco {{index}}',
    },
    ebsr: {
      part: 'Parte {{index}}',
      twoPartQuestion: 'Pregunta de dos partes',
    },
    editableHtml: {
      responseAreaToolbar: 'Área de respuesta',
      toolbar: 'Herramientas de edición',
      buttons: {
        insertTable: 'Insertar tabla',
        addTableRow: 'Agregar fila a la tabla',
        removeTableRow: 'Eliminar fila de la tabla',
        addTableColumn: 'Agregar columna a la tabla',
        removeTableColumn: 'Eliminar columna de la tabla',
        removeTable: 'Eliminar tabla',
        tableBorders: 'Bordes de la tabla',
        bold: 'Negrita',
        italic: 'Cursiva',
        strikethrough: 'Tachado',
        code: 'Código',
        underline: 'Subrayado',
        subscript: 'Subíndice',
        superscript: 'Superíndice',
        insertImage: 'Insertar imagen',
        insertVideo: 'Insertar video',
        insertAudio: 'Insertar audio',
        cssClasses: 'Clases CSS',
        blockquote: 'Cita en bloque',
        heading: 'Encabezado',
        insertMath: 'Insertar expresión matemática',
        spanishCharacters: 'Caracteres del español (ñ)',
        specialCharacters: 'Caracteres especiales (€)',
        textAlignment: 'Alineación del texto',
        bulletedList: 'Lista con viñetas',
        numberedList: 'Lista numerada',
        done: 'Listo',
      },
    },
    explicitConstructedResponse: {
      fillInTheBlankQuestion: 'Pregunta para completar espacios en blanco',
      response: 'Respuesta {{index}} de {{total}}',
    },
    extendedTextEntry: {
      comment: 'Comentario',
      constructedResponseQuestion: 'Pregunta de respuesta construida',
      response: 'Tu respuesta',
      writtenResponseQuestion: 'Pregunta de respuesta escrita',
    },
    fractionModel: {
      modelLabel_one: 'Modelo {{index}} de {{total}}: {{selected}} de {{count}} parte seleccionada',
      modelLabel_other:
        'Modelo {{index}} de {{total}}: {{selected}} de {{count}} partes seleccionadas',
    },
    numberLine: {
      addElementLimit_one: 'Solo puedes agregar {{count}} elemento',
      addElementLimit_other: 'Solo puedes agregar {{count}} elementos',
      clearAll: 'Borrar todo',
      closedEnd: 'cerrado',
      elementCorrect: 'Correcto.',
      elementIncorrect: 'Incorrecto.',
      graphLabel: 'Recta numérica de {{min}} a {{max}}, con una marca cada {{interval}}',
      line: 'Línea de {{left}} ({{leftEnd}}) a {{right}} ({{rightEnd}}).',
      openEnd: 'abierto',
      plottedNone: 'No hay nada marcado en la recta.',
      pointClosed: 'Punto cerrado en {{position}}.',
      pointOpen: 'Punto abierto en {{position}}.',
      rayLeft: 'Rayo desde {{position}} ({{end}}) hacia la izquierda.',
      rayRight: 'Rayo desde {{position}} ({{end}}) hacia la derecha.',
    },
    hotspot: {
      correctlySelected: 'Seleccionada correctamente',
      image_one: 'Imagen con {{count}} zona activa',
      image_other: 'Imagen con {{count}} zonas activas',
      shape: 'Zona activa {{index}} de {{total}}',
      shouldHaveBeenSelected: 'Debía seleccionarse',
      shouldNotHaveBeenSelected: 'No debía seleccionarse',
    },
    imageClozeAssociation: {
      answerChoice: 'Opción de respuesta {{index}} de {{total}}',
      image_one: 'Imagen con {{count}} área de respuesta',
      image_other: 'Imagen con {{count}} áreas de respuesta',
      reachedLimit_one:
        'Has alcanzado el límite de {{count}} respuesta por área. Para agregar otra respuesta, primero se debe eliminar una respuesta.',
      reachedLimit_other: 'Lleno',
      responseArea: 'Área de respuesta {{index}} de {{total}}',
    },
    inlineDropdown: {
      inlineDropdownQuestion: 'Pregunta con menú desplegable',
      query: 'Consulta',
      queryNumber: 'Consulta {{index}}',
      showRationaleForChoices: 'Mostrar justificación de las opciones',
      hideRationaleForChoices: 'Ocultar justificación de las opciones',
    },
    drawingResponse: {
      fillColor: 'Color de relleno',
      outlineColor: 'Color del contorno',
      noFill: 'Sin relleno',
      lightblue: 'Azul claro',
      lightyellow: 'Amarillo claro',
      red: 'Rojo',
      orange: 'Naranja',
      yellow: 'Amarillo',
      violet: 'Violeta',
      blue: 'Azul',
      green: 'Verde',
      white: 'Blanco',
      black: 'Negro',
      onDoubleClick:
        'Haz doble clic para revisar este texto. Presiona el botón de ingreso para enviar',
      drawingArea: 'Área de dibujo',
      drawingAreaOverImage: 'Área de dibujo sobre una imagen de fondo',
      tools: {
        select: 'Seleccionar',
        freeDraw: 'Dibujo libre',
        line: 'Línea',
        rectangle: 'Rectángulo',
        circle: 'Círculo',
        textEntry: 'Entrada de texto',
        eraser: 'Borrador',
      },
    },
    charting: {
      addCategory: 'Añadir categoría',
      actions: 'Acciones',
      add: 'Añadir',
      delete: 'Eliminar',
      newLabel: 'Nueva etiqueta',
      categoryLabel: 'Etiqueta de la categoría {{index}}',
      reachedLimit_other: 'No puede haber más de {{count}} categorías.',
      keyLegend: {
        incorrectAnswer: 'Respuesta incorrecta del estudiante',
        correctAnswer: 'Respuesta correcta del estudiante',
        correctKeyAnswer: 'Clave de respuesta correcta',
      },
      chartTypes: {
        bar: 'Gráfico de barras',
        histogram: 'Histograma',
        lineDot: 'Gráfico de líneas con puntos',
        lineCross: 'Gráfico de líneas con cruces',
        dotPlot: 'Diagrama de puntos',
        linePlot: 'Diagrama de líneas',
      },
      categories_zero: 'Sin categorías.',
      categories_one: '{{count}} categoría: {{categories}}.',
      categories_other: '{{count}} categorías: {{categories}}.',
      valueRange: 'Valores de {{min}} a {{max}}.',
      labelledValueRange: '{{label}} de {{min}} a {{max}}.',
    },
    graphing: {
      graph: 'Gráfica de coordenadas',
      axisRange: 'Eje {{axis}} de {{min}} a {{max}}.',
      plotted_zero: 'Nada trazado.',
      plotted_one: '{{count}} objeto trazado: {{marks}}.',
      plotted_other: '{{count}} objetos trazados: {{marks}}.',
      shadedRegion: 'Región sombreada',
      point: 'Punto',
      circle: 'Circulo',
      line: 'Línea',
      parabola: 'Parábola',
      absolute: 'Valor absoluto',
      exponential: 'Exponencial',
      polygon: 'Polígono',
      ray: 'Semirrecta',
      segment: 'Segmento ',
      sine: 'Seno',
      vector: 'Vector',
      label: 'Etiqueta',
      markLabel: 'Etiqueta en ({{x}}, {{y}})',
      correctMarkLabel: 'Etiqueta correcta en ({{x}}, {{y}})',
      redo: 'Rehacer',
      reset: 'Reiniciar',
      keyLegend: {
        missingRequiredLabel: 'Falta una etiqueta obligatoria',
        answerKeyCorrect: 'Clave de respuesta correcta',
        answerKeyCorrectLabel: 'Etiqueta correcta de la clave de respuesta',
        studentIncorrect: 'Respuesta incorrecta del estudiante',
        incorrectStudentLabel: 'Etiqueta incorrecta del estudiante',
        studentCorrect: 'Respuesta correcta del estudiante',
        studentCorrectLabel: 'Etiqueta correcta del estudiante',
      },
    },
    mathInline: {
      keypadInstructions:
        'Este campo admite la entrada con el teclado en pantalla y con el teclado físico. Usa el teclado físico para acceder al teclado matemático en pantalla e interactuar con él; este acepta notación LaTeX. Usa la tecla de flecha hacia abajo para abrir el teclado en pantalla y recorrer sus botones. Usa la tecla Escape para cerrar el teclado en pantalla y volver al campo de entrada.',
      mathEquationResponseQuestion: 'Pregunta de respuesta con ecuación matemática',
      mathResponseQuestion: 'Pregunta de respuesta matemática',
      primaryCorrectWithAlternates:
        'Nota: La respuesta que se muestra arriba es la respuesta correcta principal especificada por el autor para esta pregunta, pero también se pueden reconocer otras respuestas como correctas.',
    },
    mathInput: {
      enterAnswer: 'Escribe la respuesta',
    },
    mcPopulatedBlank: {
      answerChoices: 'Opciones de respuesta',
      blankLabel: 'espacio en blanco',
      emptyBlank: '(en blanco)',
      blankPreSelectionHint: 'La respuesta que elijas aparecerá en la línea en blanco de arriba.',
      correctAnswerSelected: 'Respuesta correcta seleccionada',
      incorrectAnswerSelected: 'Respuesta incorrecta seleccionada',
      selectedAnswerImage: 'Imagen de la respuesta seleccionada',
      choiceImage: 'Opción {{id}}',
      clickToEnableAutoplay: 'Haz clic para activar la reproducción automática del audio',
      audioResourceUnavailable:
        'El audio está activado, pero no hay una URL de audio reproducible configurada.',
      listen: 'Escuchar',
      listenSilentAlt: 'Escuchar. Repetir las instrucciones.',
      listenPlayingAlt: 'Escuchar. Estas son las instrucciones.',
      printAudio: 'Audio:',
      printTranscript: 'Transcripción:',
    },
    multipleChoice: {
      minSelections: 'Seleccione al menos {{minSelections}}.',
      maxSelections_one: 'Sólo se permite {{maxSelections}} respuesta.',
      maxSelections_other: 'Sólo se permiten {{maxSelections}} respuestas.',
      minmaxSelections_equal: 'Seleccione {{minSelections}}.',
      minmaxSelections_range: 'Seleccione entre {{minSelections}} y {{maxSelections}}.',
      multipleChoiceQuestion: 'Pregunta de opción múltiple',
      multipleCorrectAnswerQuestion: 'Pregunta con varias respuestas correctas',
      multipleSelectQuestion: 'Pregunta de selección múltiple',
    },
    rubric: {
      rubric: 'Rúbrica',
      showRubric: 'Mostrar rúbrica',
      hideRubric: 'Ocultar rúbrica',
    },
    selectText: {
      correctAnswerSelected: 'Respuesta Correcta',
      correctAnswerNotSelected: 'Respuesta Correcta No Seleccionada',
      incorrectSelection: 'Selección Incorrecta',
      key: 'Clave',
      textGroup: 'Texto seleccionable',
      textGroupWithLimit: 'Texto seleccionable, selecciona hasta {{max}}',
      tokenPosition: '{{index}} de {{total}}',
    },
    simpleCloze: {
      correctAnswerShown: 'Respuesta correcta',
      correct: 'Correcto',
      incorrect: 'Incorrecto',
      unanswered: 'Sin respuesta',
      placeholder: 'Escribe tu respuesta...',
      answerInput: 'Tu respuesta',
      printCorrectAnswer: 'Respuesta correcta:',
      printAnswerBlank: 'Espacio para la respuesta',
    },
    vennClassification: {
      tray: 'Fichas para clasificar',
      unknownTarget: 'desconocido',
      cancelled: 'Cancelado',
      returnedToTray: 'Se devolvió {{name}} a la bandeja',
      placedIn: 'Se colocó {{name}} en {{target}}',
      pickedUp: 'Se tomó {{name}}',
      pickedUpWithKeyboard:
        'Se tomó {{name}}, destino: {{target}}. Usa las flechas para elegir un destino, Enter para soltar y Escape para cancelar.',
      dropTarget: 'Destino: {{target}}',
      unsupportedCircles_one:
        'No se puede mostrar este diagrama: tiene {{count}} círculo, y solo se admiten {{supported}}.',
      unsupportedCircles_other:
        'No se puede mostrar este diagrama: tiene {{count}} círculos, y solo se admiten {{supported}}.',
      setNumber: 'Conjunto {{number}}',
      regionOnly: 'Solo {{set}}',
      regionNeither: 'Ni {{first}} ni {{second}}',
      regionNoneOf: 'Ninguno de {{sets}}',
      regionAndSeparator: ' y ',
      tileFallbackName: 'Ficha',
      tileNotPlaced: 'sin colocar',
      tileInRegion: 'en {{region}}',
      tileCorrect: 'correcta',
      tileIncorrect: 'incorrecta',
    },
  },
  common: {
    undo: 'Deshacer',
    clearAll: 'Borrar todo',
    correct: 'Correcto',
    incorrect: 'Incorrecto',
    showCorrectAnswer: 'Mostrar respuesta correcta',
    hideCorrectAnswer: 'Ocultar respuesta correcta',
    showTeacherInstructions: 'Mostrar instrucciones para el maestro',
    hideTeacherInstructions: 'Ocultar instrucciones para el maestro',
    show: 'Mostrar',
    hide: 'Ocultar',
    showRationale: 'Mostrar justificación',
    hideRationale: 'Ocultar justificación',
    commonCorrectAnswerWithAlternates:
      'Nota: La respuesta que se muestra arriba es la respuesta correcta más común para esta pregunta. También se definen una o más respuestas correctas adicionales, y también se reconocerán como correctas.',
    warning: 'Advertencia',
    showNote: 'Mostrar Nota',
    hideNote: 'Ocultar Nota',
    cancel: 'Cancelar',
    playAudio: 'Reproducir audio',
  },
};
