export default {
  translation: {
    categorize: {
      limitMaxChoicesPerCategory:
        'Has alcanzado el límite de {{maxChoicesPerCategory}} respuestas por área. Para agregar otra respuesta, primero se debe eliminar una respuesta.',
      maxChoicesPerCategoryRestriction:
        'Para cambiar este valor a {{maxChoicesPerCategory}}, cada categoría debe tener {{maxChoicesPerCategory}} o menos opciones de respuesta',
    },
    ebsr: {
      part: 'Parte {{index}}',
    },
    numberLine: {
      addElementLimit_one: 'Solo puedes agregar {{count}} elemento',
      addElementLimit_other: 'Solo puedes agregar {{count}} elementos',
      clearAll: 'Borrar todo',
    },
    imageClozeAssociation: {
      reachedLimit_one:
        'Has alcanzado el límite de {{count}} respuesta por área. Para agregar otra respuesta, primero se debe eliminar una respuesta.',
      reachedLimit_other: 'Lleno',
    },
    drawingResponse: {
      fillColor: 'Color de relleno',
      outlineColor: 'Color del contorno',
      noFill: 'Sin relleno',
      lightblue: 'Azul claro',
      lightyellow: 'Amarillo claro',
      red: 'Rojo',
      orange: 'Naranja',
      yellow: 'Amarillo',
      violet: 'Violeta',
      blue: 'Azul',
      green: 'Verde',
      white: 'Blanco',
      black: 'Negro',
      onDoubleClick:
        'Haz doble clic para revisar este texto. Presiona el botón de ingreso para enviar',
    },
    charting: {
      addCategory: 'Añadir categoría',
      actions: 'Acciones',
      add: 'Añadir',
      delete: 'Eliminar',
      newLabel: 'Nueva etiqueta',
      reachedLimit_other: 'No puede haber más de {{count}} categorías.',
      keyLegend: {
        incorrectAnswer: 'Respuesta incorrecta del estudiante',
        correctAnswer: 'Respuesta correcta del estudiante',
        correctKeyAnswer: 'Clave de respuesta correcta',
      },
    },
    graphing: {
      point: 'Punto',
      circle: 'Circulo',
      line: 'Línea',
      parabola: 'Parábola',
      absolute: 'Valor absoluto',
      exponential: 'Exponencial',
      polygon: 'Polígono',
      ray: 'Semirrecta',
      segment: 'Segmento ',
      sine: 'Seno',
      vector: 'Vector',
      label: 'Etiqueta',
      redo: 'Rehacer',
      reset: 'Reiniciar',
    },
    mathInline: {
      primaryCorrectWithAlternates:
        'Nota: La respuesta que se muestra arriba es la respuesta correcta principal especificada por el autor para esta pregunta, pero también se pueden reconocer otras respuestas como correctas.',
    },
    mcPopulatedBlank: {
      answerChoices: 'Opciones de respuesta',
      blankLabel: 'espacio en blanco',
      emptyBlank: '(en blanco)',
      blankPreSelectionHint: 'La respuesta que elijas aparecerá en la línea en blanco de arriba.',
      correctAnswerSelected: 'Respuesta correcta seleccionada',
      incorrectAnswerSelected: 'Respuesta incorrecta seleccionada',
      selectedAnswerImage: 'Imagen de la respuesta seleccionada',
      choiceImage: 'Opción {{id}}',
      clickToEnableAutoplay: 'Haz clic para activar la reproducción automática del audio',
      audioResourceUnavailable:
        'El audio está activado, pero no hay una URL de audio reproducible configurada.',
      listen: 'Escuchar',
      listenSilentAlt: 'Escuchar. Repetir las instrucciones.',
      listenPlayingAlt: 'Escuchar. Estas son las instrucciones.',
    },
    multipleChoice: {
      minSelections: 'Seleccione al menos {{minSelections}}.',
      maxSelections_one: 'Sólo se permite {{maxSelections}} respuesta.',
      maxSelections_other: 'Sólo se permiten {{maxSelections}} respuestas.',
      minmaxSelections_equal: 'Seleccione {{minSelections}}.',
      minmaxSelections_range: 'Seleccione entre {{minSelections}} y {{maxSelections}}.',
    },
    selectText: {
      correctAnswerSelected: 'Respuesta Correcta',
      correctAnswerNotSelected: 'Respuesta Correcta No Seleccionada',
      incorrectSelection: 'Selección Incorrecta',
      key: 'Clave',
    },
    simpleCloze: {
      correctAnswerShown: 'Respuesta correcta',
      correct: 'Correcto',
      incorrect: 'Incorrecto',
      placeholder: 'Escribe tu respuesta...',
      answerInput: 'Tu respuesta',
      printCorrectAnswer: 'Respuesta correcta:',
      printAnswerBlank: 'Espacio para la respuesta',
    },
    vennClassification: {
      tray: 'Fichas para clasificar',
      unknownTarget: 'desconocido',
      cancelled: 'Cancelado',
      returnedToTray: 'Se devolvió {{name}} a la bandeja',
      placedIn: 'Se colocó {{name}} en {{target}}',
      pickedUp: 'Se tomó {{name}}',
      pickedUpWithKeyboard:
        'Se tomó {{name}}, destino: {{target}}. Usa las flechas para elegir un destino, Enter para soltar y Escape para cancelar.',
      dropTarget: 'Destino: {{target}}',
      unsupportedCircles_one:
        'No se puede mostrar este diagrama: tiene {{count}} círculo, y solo se admiten {{supported}}.',
      unsupportedCircles_other:
        'No se puede mostrar este diagrama: tiene {{count}} círculos, y solo se admiten {{supported}}.',
      setNumber: 'Conjunto {{number}}',
      regionOnly: 'Solo {{set}}',
      regionNeither: 'Ni {{first}} ni {{second}}',
      regionNoneOf: 'Ninguno de {{sets}}',
      regionAndSeparator: ' y ',
      tileFallbackName: 'Ficha',
      tileNotPlaced: 'sin colocar',
      tileInRegion: 'en {{region}}',
      tileCorrect: 'correcta',
      tileIncorrect: 'incorrecta',
    },
  },
  common: {
    undo: 'Deshacer',
    clearAll: 'Borrar todo',
    correct: 'Correct',
    incorrect: 'Incorrect',
    showCorrectAnswer: 'Mostrar respuesta correcta',
    hideCorrectAnswer: 'Ocultar respuesta correcta',
    commonCorrectAnswerWithAlternates:
      'Nota: La respuesta que se muestra arriba es la respuesta correcta más común para esta pregunta. También se definen una o más respuestas correctas adicionales, y también se reconocerán como correctas.',
    warning: 'Advertencia',
    showNote: 'Mostrar Nota',
    hideNote: 'Ocultar Nota',
    cancel: 'Cancelar',
  },
};
