// @auto-generated by upstream:sync
// Local ESM replacement for react-input-autosize used by graph label inputs.
import React, { useCallback, useLayoutEffect, useRef, useState } from 'react';

export interface AutosizeInputProps
  extends Omit<React.InputHTMLAttributes<HTMLInputElement>, 'className' | 'style'> {
  className?: string;
  inputClassName?: string;
  inputRef?: (node: HTMLInputElement | null) => void;
  inputStyle?: React.CSSProperties;
  minWidth?: number | string;
  style?: React.CSSProperties;
}

const parsePixelValue = (value: string): number => {
  const parsed = Number.parseFloat(value);
  return Number.isFinite(parsed) ? parsed : 0;
};

const readMinWidth = (
  value: number | string | undefined,
  fallback: number | string | undefined
): number => {
  const candidate = value ?? fallback;
  if (typeof candidate === 'number') {
    return candidate;
  }
  if (typeof candidate === 'string' && candidate.endsWith('px')) {
    return parsePixelValue(candidate);
  }
  return 1;
};

export const AutosizeInput = React.forwardRef<HTMLInputElement, AutosizeInputProps>(
  (
    {
      className,
      inputClassName,
      inputRef,
      inputStyle,
      minWidth,
      placeholder,
      style,
      value,
      defaultValue,
      ...inputProps
    },
    forwardedRef
  ) => {
    const inputNodeRef = useRef<HTMLInputElement | null>(null);
    const inputRefCallbackRef = useRef(inputRef);
    const forwardedRefRef = useRef(forwardedRef);
    const measureNodeRef = useRef<HTMLSpanElement | null>(null);
    const [width, setWidth] = useState(() => readMinWidth(minWidth, inputStyle?.minWidth));

    inputRefCallbackRef.current = inputRef;
    forwardedRefRef.current = forwardedRef;

    const setInputRef = useCallback(
      (node: HTMLInputElement | null) => {
        inputNodeRef.current = node;
        inputRefCallbackRef.current?.(node);
        const currentForwardedRef = forwardedRefRef.current;
        if (typeof currentForwardedRef === 'function') {
          currentForwardedRef(node);
        } else if (currentForwardedRef) {
          (currentForwardedRef as React.MutableRefObject<HTMLInputElement | null>).current = node;
        }
      },
      []
    );

    useLayoutEffect(() => {
      const input = inputNodeRef.current;
      const measure = measureNodeRef.current;
      if (!input || !measure) {
        return;
      }

      const computed = window.getComputedStyle(input);
      measure.style.font = computed.font;
      measure.style.letterSpacing = computed.letterSpacing;
      measure.style.textTransform = computed.textTransform;
      measure.textContent = String(value ?? defaultValue ?? placeholder ?? '') || ' ';

      const horizontalPadding =
        parsePixelValue(computed.paddingLeft) +
        parsePixelValue(computed.paddingRight) +
        parsePixelValue(computed.borderLeftWidth) +
        parsePixelValue(computed.borderRightWidth);
      const measuredTextWidth = Math.ceil(measure.getBoundingClientRect().width + 2);
      const measuredWidth =
        computed.boxSizing === 'border-box'
          ? measuredTextWidth + horizontalPadding
          : measuredTextWidth;
      setWidth(Math.max(readMinWidth(minWidth, inputStyle?.minWidth), measuredWidth));
    }, [defaultValue, inputClassName, inputStyle, minWidth, placeholder, value]);

    return (
      <span className={className} style={{ display: 'inline-block', ...style }}>
        <input
          {...inputProps}
          ref={setInputRef}
          className={inputClassName}
          placeholder={placeholder}
          style={{ width, ...inputStyle }}
          value={value}
          defaultValue={defaultValue}
        />
        <span
          ref={measureNodeRef}
          aria-hidden="true"
          style={{
            height: 0,
            left: 0,
            overflow: 'hidden',
            position: 'absolute',
            top: 0,
            visibility: 'hidden',
            whiteSpace: 'pre',
          }}
        />
      </span>
    );
  }
);

AutosizeInput.displayName = 'AutosizeInput';
