/**
 * Element Registry
 *
 * AUTO-GENERATED by upstream:sync command.
 * DO NOT EDIT MANUALLY - changes will be overwritten.
 *
 * Generated: 2026-02-03T01:07:44.664Z
 */

export interface ElementMetadata {
  name: string;
  title: string;
  packageName: string;
  hasAuthor: boolean;
  hasPrint: boolean;
  hasConfig: boolean;
  hasSession: boolean;
  demoCount: number;
}

export const ELEMENT_REGISTRY: readonly ElementMetadata[] = [
  {
    "name": "categorize",
    "title": "Categorize",
    "packageName": "@pie-element/categorize",
    "hasAuthor": true,
    "hasPrint": false,
    "hasConfig": true,
    "hasSession": true,
    "demoCount": 4
  },
  {
    "name": "charting",
    "title": "Charting",
    "packageName": "@pie-element/charting",
    "hasAuthor": true,
    "hasPrint": false,
    "hasConfig": true,
    "hasSession": true,
    "demoCount": 3
  },
  {
    "name": "complex-rubric",
    "title": "Complex Rubric",
    "packageName": "@pie-element/complex-rubric",
    "hasAuthor": true,
    "hasPrint": true,
    "hasConfig": true,
    "hasSession": true,
    "demoCount": 1
  },
  {
    "name": "drag-in-the-blank",
    "title": "Drag In The Blank",
    "packageName": "@pie-element/drag-in-the-blank",
    "hasAuthor": true,
    "hasPrint": false,
    "hasConfig": true,
    "hasSession": true,
    "demoCount": 4
  },
  {
    "name": "drawing-response",
    "title": "Drawing Response",
    "packageName": "@pie-element/drawing-response",
    "hasAuthor": true,
    "hasPrint": false,
    "hasConfig": true,
    "hasSession": true,
    "demoCount": 3
  },
  {
    "name": "ebsr",
    "title": "Ebsr",
    "packageName": "@pie-element/ebsr",
    "hasAuthor": true,
    "hasPrint": true,
    "hasConfig": true,
    "hasSession": true,
    "demoCount": 3
  },
  {
    "name": "explicit-constructed-response",
    "title": "Explicit Constructed Response",
    "packageName": "@pie-element/explicit-constructed-response",
    "hasAuthor": true,
    "hasPrint": true,
    "hasConfig": true,
    "hasSession": true,
    "demoCount": 4
  },
  {
    "name": "extended-text-entry",
    "title": "Extended Text Entry",
    "packageName": "@pie-element/extended-text-entry",
    "hasAuthor": true,
    "hasPrint": true,
    "hasConfig": true,
    "hasSession": true,
    "demoCount": 4
  },
  {
    "name": "fraction-model",
    "title": "Fraction Model",
    "packageName": "@pie-element/fraction-model",
    "hasAuthor": true,
    "hasPrint": false,
    "hasConfig": true,
    "hasSession": true,
    "demoCount": 3
  },
  {
    "name": "graphing",
    "title": "Graphing",
    "packageName": "@pie-element/graphing",
    "hasAuthor": true,
    "hasPrint": false,
    "hasConfig": true,
    "hasSession": true,
    "demoCount": 3
  },
  {
    "name": "graphing-solution-set",
    "title": "Graphing Solution Set",
    "packageName": "@pie-element/graphing-solution-set",
    "hasAuthor": true,
    "hasPrint": false,
    "hasConfig": true,
    "hasSession": true,
    "demoCount": 3
  },
  {
    "name": "hotspot",
    "title": "Hotspot",
    "packageName": "@pie-element/hotspot",
    "hasAuthor": true,
    "hasPrint": false,
    "hasConfig": true,
    "hasSession": true,
    "demoCount": 3
  },
  {
    "name": "image-cloze-association",
    "title": "Image Cloze Association",
    "packageName": "@pie-element/image-cloze-association",
    "hasAuthor": true,
    "hasPrint": false,
    "hasConfig": true,
    "hasSession": true,
    "demoCount": 3
  },
  {
    "name": "inline-dropdown",
    "title": "Inline Dropdown",
    "packageName": "@pie-element/inline-dropdown",
    "hasAuthor": true,
    "hasPrint": false,
    "hasConfig": true,
    "hasSession": true,
    "demoCount": 4
  },
  {
    "name": "likert",
    "title": "Likert",
    "packageName": "@pie-element/likert",
    "hasAuthor": true,
    "hasPrint": false,
    "hasConfig": true,
    "hasSession": true,
    "demoCount": 1
  },
  {
    "name": "match",
    "title": "Match",
    "packageName": "@pie-element/match",
    "hasAuthor": true,
    "hasPrint": false,
    "hasConfig": true,
    "hasSession": true,
    "demoCount": 4
  },
  {
    "name": "match-list",
    "title": "Match List",
    "packageName": "@pie-element/match-list",
    "hasAuthor": false,
    "hasPrint": false,
    "hasConfig": true,
    "hasSession": true,
    "demoCount": 1
  },
  {
    "name": "math-inline",
    "title": "Math Inline",
    "packageName": "@pie-element/math-inline",
    "hasAuthor": true,
    "hasPrint": true,
    "hasConfig": true,
    "hasSession": true,
    "demoCount": 4
  },
  {
    "name": "math-templated",
    "title": "Math Templated",
    "packageName": "@pie-element/math-templated",
    "hasAuthor": true,
    "hasPrint": true,
    "hasConfig": true,
    "hasSession": true,
    "demoCount": 3
  },
  {
    "name": "matrix",
    "title": "Matrix",
    "packageName": "@pie-element/matrix",
    "hasAuthor": true,
    "hasPrint": false,
    "hasConfig": true,
    "hasSession": true,
    "demoCount": 1
  },
  {
    "name": "multi-trait-rubric",
    "title": "Multi Trait Rubric",
    "packageName": "@pie-element/multi-trait-rubric",
    "hasAuthor": true,
    "hasPrint": false,
    "hasConfig": true,
    "hasSession": true,
    "demoCount": 1
  },
  {
    "name": "multiple-choice",
    "title": "Multiple Choice",
    "packageName": "@pie-element/multiple-choice",
    "hasAuthor": true,
    "hasPrint": true,
    "hasConfig": true,
    "hasSession": true,
    "demoCount": 6
  },
  {
    "name": "number-line",
    "title": "Number Line",
    "packageName": "@pie-element/number-line",
    "hasAuthor": true,
    "hasPrint": false,
    "hasConfig": true,
    "hasSession": false,
    "demoCount": 4
  },
  {
    "name": "passage",
    "title": "Passage",
    "packageName": "@pie-element/passage",
    "hasAuthor": true,
    "hasPrint": true,
    "hasConfig": true,
    "hasSession": false,
    "demoCount": 1
  },
  {
    "name": "placement-ordering",
    "title": "Placement Ordering",
    "packageName": "@pie-element/placement-ordering",
    "hasAuthor": true,
    "hasPrint": false,
    "hasConfig": true,
    "hasSession": true,
    "demoCount": 4
  },
  {
    "name": "rubric",
    "title": "Rubric",
    "packageName": "@pie-element/rubric",
    "hasAuthor": true,
    "hasPrint": true,
    "hasConfig": true,
    "hasSession": false,
    "demoCount": 1
  },
  {
    "name": "select-text",
    "title": "Select Text",
    "packageName": "@pie-element/select-text",
    "hasAuthor": true,
    "hasPrint": true,
    "hasConfig": true,
    "hasSession": true,
    "demoCount": 4
  }
];

export function getElement(name: string): ElementMetadata | undefined {
  return ELEMENT_REGISTRY.find((el) => el.name === name);
}

export function getAllElements(): readonly ElementMetadata[] {
  return ELEMENT_REGISTRY;
}
