import DOMPurify from 'dompurify';

/**
 * Sanitize HTML content using DOMPurify to prevent XSS attacks
 * while allowing safe formatting, math content, and images
 */
export function sanitizeHtml(html: string): string {
  return DOMPurify.sanitize(html, {
    ALLOWED_TAGS: [
      // Block elements
      'p',
      'div',
      'br',
      'h3',
      'blockquote',
      // Lists
      'ul',
      'ol',
      'li',
      // Inline formatting
      'strong',
      'em',
      'u',
      'del',
      's',
      'sup',
      'sub',
      'b',
      'i',
      // Images
      'img',
      // Math (for KaTeX and MathML output)
      'span',
      'math',
      'semantics',
      'mrow',
      'mi',
      'mn',
      'mo',
      'msup',
      'msub',
      'mfrac',
      'msqrt',
      'mroot',
      'mtext',
      'annotation',
      'msubsup',
      'munder',
      'mover',
      'munderover',
      'mtable',
      'mtr',
      'mtd',
      'mspace',
      'mstyle',
      'menclose',
      'maction',
    ],
    ALLOWED_ATTR: [
      'class',
      'style',
      'data-latex',
      'data-alignment',
      'src',
      'alt',
      'width',
      'height',
      'align',
      'data-type',
      // MathML attributes
      'encoding',
      'mathvariant',
      'mathsize',
      'mathcolor',
      'mathbackground',
      'displaystyle',
      'scriptlevel',
      'notation',
      'open',
      'close',
      'separators',
      'subscriptshift',
      'superscriptshift',
      'accent',
      'accentunder',
      'lspace',
      'rspace',
      'stretchy',
      'symmetric',
      'maxsize',
      'minsize',
      'largeop',
      'movablelimits',
      'fence',
      'separator',
      'form',
      'href',
      'columnalign',
      'rowspan',
      'columnspan',
      'rowalign',
      'columnlines',
      'rowlines',
      'frame',
    ],
    ALLOW_DATA_ATTR: true, // For math and custom data attributes
    KEEP_CONTENT: true, // Keep text content even if tags are removed
  });
}
