// @ts-nocheck
/**
 * Element Static Imports
 *
 * AUTO-GENERATED by scripts/generate-element-imports.ts - DO NOT EDIT MANUALLY
 *
 * This file registers all available PIE elements with absolute source paths.
 * Using absolute /@fs/ paths bypasses package.json export conditions
 * and ensures dynamic imports remain portable across environments.
 *
 * IMPORTANT: We use absolute paths here instead of bare specifiers because:
 * 1. Dynamic imports with variable paths (like in demo-element-loader.ts) don't
 *    benefit from Vite's alias resolution
 * 2. Absolute /@fs/ paths work correctly in dynamic imports
 * 3. Source paths avoid build-order coupling on prebuilt dist artifacts
 *
 * The workspace resolver plugin handles resolving dependencies that the
 * element dist files import (like @pie-element/shared-math-rendering-katex)
 *
 * Generated at build-time by prebuild script
 */

// Element module registry
const elementModules = new Map();
const controllerModules = new Map();
const authorModules = new Map();
const printModules = new Map();

// Register helper functions
export function registerElement(name, importer) {
  elementModules.set(name, importer);
}

export function registerController(name, importer) {
  controllerModules.set(name, importer);
}

export function registerAuthor(name, importer) {
  authorModules.set(name, importer);
}

export function registerPrint(name, importer) {
  printModules.set(name, importer);
}

// Get helper functions
export function getElementModule(name) {
  return elementModules.get(name);
}

export function getControllerModule(name) {
  return controllerModules.get(name);
}

export function getAuthorModule(name) {
  return authorModules.get(name);
}

export function getPrintModule(name) {
  return printModules.get(name);
}

export function hasElementModule(name) {
  return elementModules.has(name);
}

// ============================================================================
// ELEMENT REGISTRATIONS
// ============================================================================

// Register element: categorize
registerElement('categorize', () =>
  import(
    /* @vite-ignore */
    '/@fs/Users/patriciaromaniuc/pie-framework/pie-elements-ng/packages/elements-react/categorize/src/index.ts'
  )
);
registerController('categorize', () =>
  import(
    /* @vite-ignore */
    '/@fs/Users/patriciaromaniuc/pie-framework/pie-elements-ng/packages/elements-react/categorize/src/controller/index.ts'
  )
);
registerAuthor('categorize', () =>
  import(
    /* @vite-ignore */
    '/@fs/Users/patriciaromaniuc/pie-framework/pie-elements-ng/packages/elements-react/categorize/src/author/index.ts'
  )
);

// Register element: charting
registerElement('charting', () =>
  import(
    /* @vite-ignore */
    '/@fs/Users/patriciaromaniuc/pie-framework/pie-elements-ng/packages/elements-react/charting/src/index.ts'
  )
);
registerController('charting', () =>
  import(
    /* @vite-ignore */
    '/@fs/Users/patriciaromaniuc/pie-framework/pie-elements-ng/packages/elements-react/charting/src/controller/index.ts'
  )
);
registerAuthor('charting', () =>
  import(
    /* @vite-ignore */
    '/@fs/Users/patriciaromaniuc/pie-framework/pie-elements-ng/packages/elements-react/charting/src/author/index.ts'
  )
);

// Register element: complex-rubric
registerElement('complex-rubric', () =>
  import(
    /* @vite-ignore */
    '/@fs/Users/patriciaromaniuc/pie-framework/pie-elements-ng/packages/elements-react/complex-rubric/src/index.ts'
  )
);
registerController('complex-rubric', () =>
  import(
    /* @vite-ignore */
    '/@fs/Users/patriciaromaniuc/pie-framework/pie-elements-ng/packages/elements-react/complex-rubric/src/controller/index.ts'
  )
);
registerAuthor('complex-rubric', () =>
  import(
    /* @vite-ignore */
    '/@fs/Users/patriciaromaniuc/pie-framework/pie-elements-ng/packages/elements-react/complex-rubric/src/author/index.ts'
  )
);
registerPrint('complex-rubric', () =>
  import(
    /* @vite-ignore */
    '/@fs/Users/patriciaromaniuc/pie-framework/pie-elements-ng/packages/elements-react/complex-rubric/src/print/index.ts'
  )
);

// Register element: drag-in-the-blank
registerElement('drag-in-the-blank', () =>
  import(
    /* @vite-ignore */
    '/@fs/Users/patriciaromaniuc/pie-framework/pie-elements-ng/packages/elements-react/drag-in-the-blank/src/index.ts'
  )
);
registerController('drag-in-the-blank', () =>
  import(
    /* @vite-ignore */
    '/@fs/Users/patriciaromaniuc/pie-framework/pie-elements-ng/packages/elements-react/drag-in-the-blank/src/controller/index.ts'
  )
);
registerAuthor('drag-in-the-blank', () =>
  import(
    /* @vite-ignore */
    '/@fs/Users/patriciaromaniuc/pie-framework/pie-elements-ng/packages/elements-react/drag-in-the-blank/src/author/index.tsx'
  )
);

// Register element: drawing-response
registerElement('drawing-response', () =>
  import(
    /* @vite-ignore */
    '/@fs/Users/patriciaromaniuc/pie-framework/pie-elements-ng/packages/elements-react/drawing-response/src/index.ts'
  )
);
registerController('drawing-response', () =>
  import(
    /* @vite-ignore */
    '/@fs/Users/patriciaromaniuc/pie-framework/pie-elements-ng/packages/elements-react/drawing-response/src/controller/index.ts'
  )
);
registerAuthor('drawing-response', () =>
  import(
    /* @vite-ignore */
    '/@fs/Users/patriciaromaniuc/pie-framework/pie-elements-ng/packages/elements-react/drawing-response/src/author/index.ts'
  )
);

// Register element: ebsr
registerElement('ebsr', () =>
  import(
    /* @vite-ignore */
    '/@fs/Users/patriciaromaniuc/pie-framework/pie-elements-ng/packages/elements-react/ebsr/src/index.ts'
  )
);
registerController('ebsr', () =>
  import(
    /* @vite-ignore */
    '/@fs/Users/patriciaromaniuc/pie-framework/pie-elements-ng/packages/elements-react/ebsr/src/controller/index.ts'
  )
);
registerAuthor('ebsr', () =>
  import(
    /* @vite-ignore */
    '/@fs/Users/patriciaromaniuc/pie-framework/pie-elements-ng/packages/elements-react/ebsr/src/author/index.ts'
  )
);
registerPrint('ebsr', () =>
  import(
    /* @vite-ignore */
    '/@fs/Users/patriciaromaniuc/pie-framework/pie-elements-ng/packages/elements-react/ebsr/src/print/index.tsx'
  )
);

// Register element: explicit-constructed-response
registerElement('explicit-constructed-response', () =>
  import(
    /* @vite-ignore */
    '/@fs/Users/patriciaromaniuc/pie-framework/pie-elements-ng/packages/elements-react/explicit-constructed-response/src/index.ts'
  )
);
registerController('explicit-constructed-response', () =>
  import(
    /* @vite-ignore */
    '/@fs/Users/patriciaromaniuc/pie-framework/pie-elements-ng/packages/elements-react/explicit-constructed-response/src/controller/index.ts'
  )
);
registerAuthor('explicit-constructed-response', () =>
  import(
    /* @vite-ignore */
    '/@fs/Users/patriciaromaniuc/pie-framework/pie-elements-ng/packages/elements-react/explicit-constructed-response/src/author/index.ts'
  )
);
registerPrint('explicit-constructed-response', () =>
  import(
    /* @vite-ignore */
    '/@fs/Users/patriciaromaniuc/pie-framework/pie-elements-ng/packages/elements-react/explicit-constructed-response/src/print/index.tsx'
  )
);

// Register element: extended-text-entry
registerElement('extended-text-entry', () =>
  import(
    /* @vite-ignore */
    '/@fs/Users/patriciaromaniuc/pie-framework/pie-elements-ng/packages/elements-react/extended-text-entry/src/index.ts'
  )
);
registerController('extended-text-entry', () =>
  import(
    /* @vite-ignore */
    '/@fs/Users/patriciaromaniuc/pie-framework/pie-elements-ng/packages/elements-react/extended-text-entry/src/controller/index.ts'
  )
);
registerAuthor('extended-text-entry', () =>
  import(
    /* @vite-ignore */
    '/@fs/Users/patriciaromaniuc/pie-framework/pie-elements-ng/packages/elements-react/extended-text-entry/src/author/index.ts'
  )
);
registerPrint('extended-text-entry', () =>
  import(
    /* @vite-ignore */
    '/@fs/Users/patriciaromaniuc/pie-framework/pie-elements-ng/packages/elements-react/extended-text-entry/src/print/index.tsx'
  )
);

// Register element: fraction-model
registerElement('fraction-model', () =>
  import(
    /* @vite-ignore */
    '/@fs/Users/patriciaromaniuc/pie-framework/pie-elements-ng/packages/elements-react/fraction-model/src/index.ts'
  )
);
registerController('fraction-model', () =>
  import(
    /* @vite-ignore */
    '/@fs/Users/patriciaromaniuc/pie-framework/pie-elements-ng/packages/elements-react/fraction-model/src/controller/index.ts'
  )
);
registerAuthor('fraction-model', () =>
  import(
    /* @vite-ignore */
    '/@fs/Users/patriciaromaniuc/pie-framework/pie-elements-ng/packages/elements-react/fraction-model/src/author/index.ts'
  )
);

// Register element: graphing
registerElement('graphing', () =>
  import(
    /* @vite-ignore */
    '/@fs/Users/patriciaromaniuc/pie-framework/pie-elements-ng/packages/elements-react/graphing/src/index.ts'
  )
);
registerController('graphing', () =>
  import(
    /* @vite-ignore */
    '/@fs/Users/patriciaromaniuc/pie-framework/pie-elements-ng/packages/elements-react/graphing/src/controller/index.ts'
  )
);
registerAuthor('graphing', () =>
  import(
    /* @vite-ignore */
    '/@fs/Users/patriciaromaniuc/pie-framework/pie-elements-ng/packages/elements-react/graphing/src/author/index.ts'
  )
);

// Register element: graphing-solution-set
registerElement('graphing-solution-set', () =>
  import(
    /* @vite-ignore */
    '/@fs/Users/patriciaromaniuc/pie-framework/pie-elements-ng/packages/elements-react/graphing-solution-set/src/index.ts'
  )
);
registerController('graphing-solution-set', () =>
  import(
    /* @vite-ignore */
    '/@fs/Users/patriciaromaniuc/pie-framework/pie-elements-ng/packages/elements-react/graphing-solution-set/src/controller/index.ts'
  )
);
registerAuthor('graphing-solution-set', () =>
  import(
    /* @vite-ignore */
    '/@fs/Users/patriciaromaniuc/pie-framework/pie-elements-ng/packages/elements-react/graphing-solution-set/src/author/index.ts'
  )
);

// Register element: hotspot
registerElement('hotspot', () =>
  import(
    /* @vite-ignore */
    '/@fs/Users/patriciaromaniuc/pie-framework/pie-elements-ng/packages/elements-react/hotspot/src/index.ts'
  )
);
registerController('hotspot', () =>
  import(
    /* @vite-ignore */
    '/@fs/Users/patriciaromaniuc/pie-framework/pie-elements-ng/packages/elements-react/hotspot/src/controller/index.ts'
  )
);
registerAuthor('hotspot', () =>
  import(
    /* @vite-ignore */
    '/@fs/Users/patriciaromaniuc/pie-framework/pie-elements-ng/packages/elements-react/hotspot/src/author/index.ts'
  )
);

// Register element: image-cloze-association
registerElement('image-cloze-association', () =>
  import(
    /* @vite-ignore */
    '/@fs/Users/patriciaromaniuc/pie-framework/pie-elements-ng/packages/elements-react/image-cloze-association/src/index.ts'
  )
);
registerController('image-cloze-association', () =>
  import(
    /* @vite-ignore */
    '/@fs/Users/patriciaromaniuc/pie-framework/pie-elements-ng/packages/elements-react/image-cloze-association/src/controller/index.ts'
  )
);
registerAuthor('image-cloze-association', () =>
  import(
    /* @vite-ignore */
    '/@fs/Users/patriciaromaniuc/pie-framework/pie-elements-ng/packages/elements-react/image-cloze-association/src/author/index.ts'
  )
);

// Register element: inline-dropdown
registerElement('inline-dropdown', () =>
  import(
    /* @vite-ignore */
    '/@fs/Users/patriciaromaniuc/pie-framework/pie-elements-ng/packages/elements-react/inline-dropdown/src/index.ts'
  )
);
registerController('inline-dropdown', () =>
  import(
    /* @vite-ignore */
    '/@fs/Users/patriciaromaniuc/pie-framework/pie-elements-ng/packages/elements-react/inline-dropdown/src/controller/index.ts'
  )
);
registerAuthor('inline-dropdown', () =>
  import(
    /* @vite-ignore */
    '/@fs/Users/patriciaromaniuc/pie-framework/pie-elements-ng/packages/elements-react/inline-dropdown/src/author/index.ts'
  )
);

// Register element: likert
registerElement('likert', () =>
  import(
    /* @vite-ignore */
    '/@fs/Users/patriciaromaniuc/pie-framework/pie-elements-ng/packages/elements-react/likert/src/index.ts'
  )
);
registerController('likert', () =>
  import(
    /* @vite-ignore */
    '/@fs/Users/patriciaromaniuc/pie-framework/pie-elements-ng/packages/elements-react/likert/src/controller/index.ts'
  )
);
registerAuthor('likert', () =>
  import(
    /* @vite-ignore */
    '/@fs/Users/patriciaromaniuc/pie-framework/pie-elements-ng/packages/elements-react/likert/src/author/index.ts'
  )
);

// Register element: match
registerElement('match', () =>
  import(
    /* @vite-ignore */
    '/@fs/Users/patriciaromaniuc/pie-framework/pie-elements-ng/packages/elements-react/match/src/index.ts'
  )
);
registerController('match', () =>
  import(
    /* @vite-ignore */
    '/@fs/Users/patriciaromaniuc/pie-framework/pie-elements-ng/packages/elements-react/match/src/controller/index.ts'
  )
);
registerAuthor('match', () =>
  import(
    /* @vite-ignore */
    '/@fs/Users/patriciaromaniuc/pie-framework/pie-elements-ng/packages/elements-react/match/src/author/index.ts'
  )
);

// Register element: match-list
registerElement('match-list', () =>
  import(
    /* @vite-ignore */
    '/@fs/Users/patriciaromaniuc/pie-framework/pie-elements-ng/packages/elements-react/match-list/src/index.ts'
  )
);
registerController('match-list', () =>
  import(
    /* @vite-ignore */
    '/@fs/Users/patriciaromaniuc/pie-framework/pie-elements-ng/packages/elements-react/match-list/src/controller/index.ts'
  )
);

// Register element: math-inline
registerElement('math-inline', () =>
  import(
    /* @vite-ignore */
    '/@fs/Users/patriciaromaniuc/pie-framework/pie-elements-ng/packages/elements-react/math-inline/src/index.ts'
  )
);
registerController('math-inline', () =>
  import(
    /* @vite-ignore */
    '/@fs/Users/patriciaromaniuc/pie-framework/pie-elements-ng/packages/elements-react/math-inline/src/controller/index.ts'
  )
);
registerAuthor('math-inline', () =>
  import(
    /* @vite-ignore */
    '/@fs/Users/patriciaromaniuc/pie-framework/pie-elements-ng/packages/elements-react/math-inline/src/author/index.ts'
  )
);
registerPrint('math-inline', () =>
  import(
    /* @vite-ignore */
    '/@fs/Users/patriciaromaniuc/pie-framework/pie-elements-ng/packages/elements-react/math-inline/src/print/index.tsx'
  )
);

// Register element: math-templated
registerElement('math-templated', () =>
  import(
    /* @vite-ignore */
    '/@fs/Users/patriciaromaniuc/pie-framework/pie-elements-ng/packages/elements-react/math-templated/src/index.ts'
  )
);
registerController('math-templated', () =>
  import(
    /* @vite-ignore */
    '/@fs/Users/patriciaromaniuc/pie-framework/pie-elements-ng/packages/elements-react/math-templated/src/controller/index.ts'
  )
);
registerAuthor('math-templated', () =>
  import(
    /* @vite-ignore */
    '/@fs/Users/patriciaromaniuc/pie-framework/pie-elements-ng/packages/elements-react/math-templated/src/author/index.ts'
  )
);
registerPrint('math-templated', () =>
  import(
    /* @vite-ignore */
    '/@fs/Users/patriciaromaniuc/pie-framework/pie-elements-ng/packages/elements-react/math-templated/src/print/index.tsx'
  )
);

// Register element: matrix
registerElement('matrix', () =>
  import(
    /* @vite-ignore */
    '/@fs/Users/patriciaromaniuc/pie-framework/pie-elements-ng/packages/elements-react/matrix/src/index.ts'
  )
);
registerController('matrix', () =>
  import(
    /* @vite-ignore */
    '/@fs/Users/patriciaromaniuc/pie-framework/pie-elements-ng/packages/elements-react/matrix/src/controller/index.ts'
  )
);
registerAuthor('matrix', () =>
  import(
    /* @vite-ignore */
    '/@fs/Users/patriciaromaniuc/pie-framework/pie-elements-ng/packages/elements-react/matrix/src/author/index.ts'
  )
);

// Register element: multi-trait-rubric
registerElement('multi-trait-rubric', () =>
  import(
    /* @vite-ignore */
    '/@fs/Users/patriciaromaniuc/pie-framework/pie-elements-ng/packages/elements-react/multi-trait-rubric/src/index.ts'
  )
);
registerController('multi-trait-rubric', () =>
  import(
    /* @vite-ignore */
    '/@fs/Users/patriciaromaniuc/pie-framework/pie-elements-ng/packages/elements-react/multi-trait-rubric/src/controller/index.ts'
  )
);
registerAuthor('multi-trait-rubric', () =>
  import(
    /* @vite-ignore */
    '/@fs/Users/patriciaromaniuc/pie-framework/pie-elements-ng/packages/elements-react/multi-trait-rubric/src/author/index.ts'
  )
);

// Register element: multiple-choice
registerElement('multiple-choice', () =>
  import(
    /* @vite-ignore */
    '/@fs/Users/patriciaromaniuc/pie-framework/pie-elements-ng/packages/elements-react/multiple-choice/src/index.ts'
  )
);
registerController('multiple-choice', () =>
  import(
    /* @vite-ignore */
    '/@fs/Users/patriciaromaniuc/pie-framework/pie-elements-ng/packages/elements-react/multiple-choice/src/controller/index.ts'
  )
);
registerAuthor('multiple-choice', () =>
  import(
    /* @vite-ignore */
    '/@fs/Users/patriciaromaniuc/pie-framework/pie-elements-ng/packages/elements-react/multiple-choice/src/author/index.ts'
  )
);
registerPrint('multiple-choice', () =>
  import(
    /* @vite-ignore */
    '/@fs/Users/patriciaromaniuc/pie-framework/pie-elements-ng/packages/elements-react/multiple-choice/src/print/index.tsx'
  )
);

// Register element: number-line
registerElement('number-line', () =>
  import(
    /* @vite-ignore */
    '/@fs/Users/patriciaromaniuc/pie-framework/pie-elements-ng/packages/elements-react/number-line/src/index.ts'
  )
);
registerController('number-line', () =>
  import(
    /* @vite-ignore */
    '/@fs/Users/patriciaromaniuc/pie-framework/pie-elements-ng/packages/elements-react/number-line/src/controller/index.ts'
  )
);
registerAuthor('number-line', () =>
  import(
    /* @vite-ignore */
    '/@fs/Users/patriciaromaniuc/pie-framework/pie-elements-ng/packages/elements-react/number-line/src/author/index.ts'
  )
);

// Register element: passage
registerElement('passage', () =>
  import(
    /* @vite-ignore */
    '/@fs/Users/patriciaromaniuc/pie-framework/pie-elements-ng/packages/elements-react/passage/src/index.ts'
  )
);
registerController('passage', () =>
  import(
    /* @vite-ignore */
    '/@fs/Users/patriciaromaniuc/pie-framework/pie-elements-ng/packages/elements-react/passage/src/controller/index.ts'
  )
);
registerAuthor('passage', () =>
  import(
    /* @vite-ignore */
    '/@fs/Users/patriciaromaniuc/pie-framework/pie-elements-ng/packages/elements-react/passage/src/author/index.ts'
  )
);
registerPrint('passage', () =>
  import(
    /* @vite-ignore */
    '/@fs/Users/patriciaromaniuc/pie-framework/pie-elements-ng/packages/elements-react/passage/src/print/index.tsx'
  )
);

// Register element: placement-ordering
registerElement('placement-ordering', () =>
  import(
    /* @vite-ignore */
    '/@fs/Users/patriciaromaniuc/pie-framework/pie-elements-ng/packages/elements-react/placement-ordering/src/index.ts'
  )
);
registerController('placement-ordering', () =>
  import(
    /* @vite-ignore */
    '/@fs/Users/patriciaromaniuc/pie-framework/pie-elements-ng/packages/elements-react/placement-ordering/src/controller/index.ts'
  )
);
registerAuthor('placement-ordering', () =>
  import(
    /* @vite-ignore */
    '/@fs/Users/patriciaromaniuc/pie-framework/pie-elements-ng/packages/elements-react/placement-ordering/src/author/index.ts'
  )
);

// Register element: rubric
registerElement('rubric', () =>
  import(
    /* @vite-ignore */
    '/@fs/Users/patriciaromaniuc/pie-framework/pie-elements-ng/packages/elements-react/rubric/src/index.ts'
  )
);
registerController('rubric', () =>
  import(
    /* @vite-ignore */
    '/@fs/Users/patriciaromaniuc/pie-framework/pie-elements-ng/packages/elements-react/rubric/src/controller/index.ts'
  )
);
registerAuthor('rubric', () =>
  import(
    /* @vite-ignore */
    '/@fs/Users/patriciaromaniuc/pie-framework/pie-elements-ng/packages/elements-react/rubric/src/author/index.ts'
  )
);
registerPrint('rubric', () =>
  import(
    /* @vite-ignore */
    '/@fs/Users/patriciaromaniuc/pie-framework/pie-elements-ng/packages/elements-react/rubric/src/print/index.tsx'
  )
);

// Register element: select-text
registerElement('select-text', () =>
  import(
    /* @vite-ignore */
    '/@fs/Users/patriciaromaniuc/pie-framework/pie-elements-ng/packages/elements-react/select-text/src/index.ts'
  )
);
registerController('select-text', () =>
  import(
    /* @vite-ignore */
    '/@fs/Users/patriciaromaniuc/pie-framework/pie-elements-ng/packages/elements-react/select-text/src/controller/index.ts'
  )
);
registerAuthor('select-text', () =>
  import(
    /* @vite-ignore */
    '/@fs/Users/patriciaromaniuc/pie-framework/pie-elements-ng/packages/elements-react/select-text/src/author/index.ts'
  )
);
registerPrint('select-text', () =>
  import(
    /* @vite-ignore */
    '/@fs/Users/patriciaromaniuc/pie-framework/pie-elements-ng/packages/elements-react/select-text/src/print/index.tsx'
  )
);
