/**
 * Element Static Imports - Type Declarations
 *
 * AUTO-GENERATED by scripts/generate-element-imports.ts - DO NOT EDIT MANUALLY
 * Generated: 2026-02-16T02:23:34.396Z
 */

export type ModuleImporter = () => Promise<any>;

export function registerElement(name: string, importer: ModuleImporter): void;
export function registerController(name: string, importer: ModuleImporter): void;
export function registerAuthor(name: string, importer: ModuleImporter): void;
export function registerPrint(name: string, importer: ModuleImporter): void;

export function getElementModule(name: string): ModuleImporter | undefined;
export function getControllerModule(name: string): ModuleImporter | undefined;
export function getAuthorModule(name: string): ModuleImporter | undefined;
export function getPrintModule(name: string): ModuleImporter | undefined;
export function hasElementModule(name: string): boolean;
