// @ts-nocheck
/**
 * Element Static Imports
 *
 * AUTO-GENERATED by scripts/generate-element-imports.ts - DO NOT EDIT MANUALLY
 *
 * This file registers all available PIE elements with absolute paths.
 * Using absolute /@fs/ paths bypasses package.json export conditions
 * and ensures we load BUILT dist files for elements.
 *
 * IMPORTANT: We use absolute paths here instead of bare specifiers because:
 * 1. Dynamic imports with variable paths (like in demo-element-loader.ts) don't
 *    benefit from Vite's alias resolution
 * 2. Absolute /@fs/ paths work correctly in dynamic imports
 * 3. This ensures we load DIST files (fully built) instead of source files
 *
 * The workspace resolver plugin handles resolving dependencies that the
 * element dist files import (like @pie-element/shared-math-rendering-katex)
 *
 * Generated: 2026-02-16T00:50:30.131Z
 */

// Element module registry
const elementModules = new Map();
const controllerModules = new Map();
const authorModules = new Map();
const printModules = new Map();

// Register helper functions
export function registerElement(name, importer) {
  elementModules.set(name, importer);
}

export function registerController(name, importer) {
  controllerModules.set(name, importer);
}

export function registerAuthor(name, importer) {
  authorModules.set(name, importer);
}

export function registerPrint(name, importer) {
  printModules.set(name, importer);
}

// Get helper functions
export function getElementModule(name) {
  return elementModules.get(name);
}

export function getControllerModule(name) {
  return controllerModules.get(name);
}

export function getAuthorModule(name) {
  return authorModules.get(name);
}

export function getPrintModule(name) {
  return printModules.get(name);
}

export function hasElementModule(name) {
  return elementModules.has(name);
}

// ============================================================================
// ELEMENT REGISTRATIONS
// ============================================================================

// Register element: categorize
registerElement(
  'categorize',
  () =>
    import(
      /* @vite-ignore */
      '/@fs/Users/eelco.hillenius/dev/prj/pie/pie-elements-ng/packages/elements-react/categorize/dist/index.js'
    )
);
registerController(
  'categorize',
  () =>
    import(
      /* @vite-ignore */
      '/@fs/Users/eelco.hillenius/dev/prj/pie/pie-elements-ng/packages/elements-react/categorize/dist/controller/index.js'
    )
);
registerAuthor(
  'categorize',
  () =>
    import(
      /* @vite-ignore */
      '/@fs/Users/eelco.hillenius/dev/prj/pie/pie-elements-ng/packages/elements-react/categorize/dist/author/index.js'
    )
);

// Register element: charting
registerElement(
  'charting',
  () =>
    import(
      /* @vite-ignore */
      '/@fs/Users/eelco.hillenius/dev/prj/pie/pie-elements-ng/packages/elements-react/charting/dist/index.js'
    )
);
registerController(
  'charting',
  () =>
    import(
      /* @vite-ignore */
      '/@fs/Users/eelco.hillenius/dev/prj/pie/pie-elements-ng/packages/elements-react/charting/dist/controller/index.js'
    )
);
registerAuthor(
  'charting',
  () =>
    import(
      /* @vite-ignore */
      '/@fs/Users/eelco.hillenius/dev/prj/pie/pie-elements-ng/packages/elements-react/charting/dist/author/index.js'
    )
);

// Register element: complex-rubric
registerElement(
  'complex-rubric',
  () =>
    import(
      /* @vite-ignore */
      '/@fs/Users/eelco.hillenius/dev/prj/pie/pie-elements-ng/packages/elements-react/complex-rubric/dist/index.js'
    )
);
registerController(
  'complex-rubric',
  () =>
    import(
      /* @vite-ignore */
      '/@fs/Users/eelco.hillenius/dev/prj/pie/pie-elements-ng/packages/elements-react/complex-rubric/dist/controller/index.js'
    )
);
registerAuthor(
  'complex-rubric',
  () =>
    import(
      /* @vite-ignore */
      '/@fs/Users/eelco.hillenius/dev/prj/pie/pie-elements-ng/packages/elements-react/complex-rubric/dist/author/index.js'
    )
);
registerPrint(
  'complex-rubric',
  () =>
    import(
      /* @vite-ignore */
      '/@fs/Users/eelco.hillenius/dev/prj/pie/pie-elements-ng/packages/elements-react/complex-rubric/dist/print/index.js'
    )
);

// Register element: drag-in-the-blank
registerElement(
  'drag-in-the-blank',
  () =>
    import(
      /* @vite-ignore */
      '/@fs/Users/eelco.hillenius/dev/prj/pie/pie-elements-ng/packages/elements-react/drag-in-the-blank/dist/index.js'
    )
);
registerController(
  'drag-in-the-blank',
  () =>
    import(
      /* @vite-ignore */
      '/@fs/Users/eelco.hillenius/dev/prj/pie/pie-elements-ng/packages/elements-react/drag-in-the-blank/dist/controller/index.js'
    )
);
registerAuthor(
  'drag-in-the-blank',
  () =>
    import(
      /* @vite-ignore */
      '/@fs/Users/eelco.hillenius/dev/prj/pie/pie-elements-ng/packages/elements-react/drag-in-the-blank/dist/author/index.js'
    )
);

// Register element: drawing-response
registerElement(
  'drawing-response',
  () =>
    import(
      /* @vite-ignore */
      '/@fs/Users/eelco.hillenius/dev/prj/pie/pie-elements-ng/packages/elements-react/drawing-response/dist/index.js'
    )
);
registerController(
  'drawing-response',
  () =>
    import(
      /* @vite-ignore */
      '/@fs/Users/eelco.hillenius/dev/prj/pie/pie-elements-ng/packages/elements-react/drawing-response/dist/controller/index.js'
    )
);
registerAuthor(
  'drawing-response',
  () =>
    import(
      /* @vite-ignore */
      '/@fs/Users/eelco.hillenius/dev/prj/pie/pie-elements-ng/packages/elements-react/drawing-response/dist/author/index.js'
    )
);

// Register element: ebsr
registerElement(
  'ebsr',
  () =>
    import(
      /* @vite-ignore */
      '/@fs/Users/eelco.hillenius/dev/prj/pie/pie-elements-ng/packages/elements-react/ebsr/dist/index.js'
    )
);
registerController(
  'ebsr',
  () =>
    import(
      /* @vite-ignore */
      '/@fs/Users/eelco.hillenius/dev/prj/pie/pie-elements-ng/packages/elements-react/ebsr/dist/controller/index.js'
    )
);
registerAuthor(
  'ebsr',
  () =>
    import(
      /* @vite-ignore */
      '/@fs/Users/eelco.hillenius/dev/prj/pie/pie-elements-ng/packages/elements-react/ebsr/dist/author/index.js'
    )
);
registerPrint(
  'ebsr',
  () =>
    import(
      /* @vite-ignore */
      '/@fs/Users/eelco.hillenius/dev/prj/pie/pie-elements-ng/packages/elements-react/ebsr/dist/print/index.js'
    )
);

// Register element: explicit-constructed-response
registerElement(
  'explicit-constructed-response',
  () =>
    import(
      /* @vite-ignore */
      '/@fs/Users/eelco.hillenius/dev/prj/pie/pie-elements-ng/packages/elements-react/explicit-constructed-response/dist/index.js'
    )
);
registerController(
  'explicit-constructed-response',
  () =>
    import(
      /* @vite-ignore */
      '/@fs/Users/eelco.hillenius/dev/prj/pie/pie-elements-ng/packages/elements-react/explicit-constructed-response/dist/controller/index.js'
    )
);
registerAuthor(
  'explicit-constructed-response',
  () =>
    import(
      /* @vite-ignore */
      '/@fs/Users/eelco.hillenius/dev/prj/pie/pie-elements-ng/packages/elements-react/explicit-constructed-response/dist/author/index.js'
    )
);
registerPrint(
  'explicit-constructed-response',
  () =>
    import(
      /* @vite-ignore */
      '/@fs/Users/eelco.hillenius/dev/prj/pie/pie-elements-ng/packages/elements-react/explicit-constructed-response/dist/print/index.js'
    )
);

// Register element: extended-text-entry
registerElement(
  'extended-text-entry',
  () =>
    import(
      /* @vite-ignore */
      '/@fs/Users/eelco.hillenius/dev/prj/pie/pie-elements-ng/packages/elements-react/extended-text-entry/dist/index.js'
    )
);
registerController(
  'extended-text-entry',
  () =>
    import(
      /* @vite-ignore */
      '/@fs/Users/eelco.hillenius/dev/prj/pie/pie-elements-ng/packages/elements-react/extended-text-entry/dist/controller/index.js'
    )
);
registerAuthor(
  'extended-text-entry',
  () =>
    import(
      /* @vite-ignore */
      '/@fs/Users/eelco.hillenius/dev/prj/pie/pie-elements-ng/packages/elements-react/extended-text-entry/dist/author/index.js'
    )
);
registerPrint(
  'extended-text-entry',
  () =>
    import(
      /* @vite-ignore */
      '/@fs/Users/eelco.hillenius/dev/prj/pie/pie-elements-ng/packages/elements-react/extended-text-entry/dist/print/index.js'
    )
);

// Register element: fraction-model
registerElement(
  'fraction-model',
  () =>
    import(
      /* @vite-ignore */
      '/@fs/Users/eelco.hillenius/dev/prj/pie/pie-elements-ng/packages/elements-react/fraction-model/dist/index.js'
    )
);
registerController(
  'fraction-model',
  () =>
    import(
      /* @vite-ignore */
      '/@fs/Users/eelco.hillenius/dev/prj/pie/pie-elements-ng/packages/elements-react/fraction-model/dist/controller/index.js'
    )
);
registerAuthor(
  'fraction-model',
  () =>
    import(
      /* @vite-ignore */
      '/@fs/Users/eelco.hillenius/dev/prj/pie/pie-elements-ng/packages/elements-react/fraction-model/dist/author/index.js'
    )
);

// Register element: graphing
registerElement(
  'graphing',
  () =>
    import(
      /* @vite-ignore */
      '/@fs/Users/eelco.hillenius/dev/prj/pie/pie-elements-ng/packages/elements-react/graphing/dist/index.js'
    )
);
registerController(
  'graphing',
  () =>
    import(
      /* @vite-ignore */
      '/@fs/Users/eelco.hillenius/dev/prj/pie/pie-elements-ng/packages/elements-react/graphing/dist/controller/index.js'
    )
);
registerAuthor(
  'graphing',
  () =>
    import(
      /* @vite-ignore */
      '/@fs/Users/eelco.hillenius/dev/prj/pie/pie-elements-ng/packages/elements-react/graphing/dist/author/index.js'
    )
);

// Register element: graphing-solution-set
registerElement(
  'graphing-solution-set',
  () =>
    import(
      /* @vite-ignore */
      '/@fs/Users/eelco.hillenius/dev/prj/pie/pie-elements-ng/packages/elements-react/graphing-solution-set/dist/index.js'
    )
);
registerController(
  'graphing-solution-set',
  () =>
    import(
      /* @vite-ignore */
      '/@fs/Users/eelco.hillenius/dev/prj/pie/pie-elements-ng/packages/elements-react/graphing-solution-set/dist/controller/index.js'
    )
);
registerAuthor(
  'graphing-solution-set',
  () =>
    import(
      /* @vite-ignore */
      '/@fs/Users/eelco.hillenius/dev/prj/pie/pie-elements-ng/packages/elements-react/graphing-solution-set/dist/author/index.js'
    )
);

// Register element: hotspot
registerElement(
  'hotspot',
  () =>
    import(
      /* @vite-ignore */
      '/@fs/Users/eelco.hillenius/dev/prj/pie/pie-elements-ng/packages/elements-react/hotspot/dist/index.js'
    )
);
registerController(
  'hotspot',
  () =>
    import(
      /* @vite-ignore */
      '/@fs/Users/eelco.hillenius/dev/prj/pie/pie-elements-ng/packages/elements-react/hotspot/dist/controller/index.js'
    )
);
registerAuthor(
  'hotspot',
  () =>
    import(
      /* @vite-ignore */
      '/@fs/Users/eelco.hillenius/dev/prj/pie/pie-elements-ng/packages/elements-react/hotspot/dist/author/index.js'
    )
);

// Register element: image-cloze-association
registerElement(
  'image-cloze-association',
  () =>
    import(
      /* @vite-ignore */
      '/@fs/Users/eelco.hillenius/dev/prj/pie/pie-elements-ng/packages/elements-react/image-cloze-association/dist/index.js'
    )
);
registerController(
  'image-cloze-association',
  () =>
    import(
      /* @vite-ignore */
      '/@fs/Users/eelco.hillenius/dev/prj/pie/pie-elements-ng/packages/elements-react/image-cloze-association/dist/controller/index.js'
    )
);
registerAuthor(
  'image-cloze-association',
  () =>
    import(
      /* @vite-ignore */
      '/@fs/Users/eelco.hillenius/dev/prj/pie/pie-elements-ng/packages/elements-react/image-cloze-association/dist/author/index.js'
    )
);

// Register element: inline-dropdown
registerElement(
  'inline-dropdown',
  () =>
    import(
      /* @vite-ignore */
      '/@fs/Users/eelco.hillenius/dev/prj/pie/pie-elements-ng/packages/elements-react/inline-dropdown/dist/index.js'
    )
);
registerController(
  'inline-dropdown',
  () =>
    import(
      /* @vite-ignore */
      '/@fs/Users/eelco.hillenius/dev/prj/pie/pie-elements-ng/packages/elements-react/inline-dropdown/dist/controller/index.js'
    )
);
registerAuthor(
  'inline-dropdown',
  () =>
    import(
      /* @vite-ignore */
      '/@fs/Users/eelco.hillenius/dev/prj/pie/pie-elements-ng/packages/elements-react/inline-dropdown/dist/author/index.js'
    )
);

// Register element: likert
registerElement(
  'likert',
  () =>
    import(
      /* @vite-ignore */
      '/@fs/Users/eelco.hillenius/dev/prj/pie/pie-elements-ng/packages/elements-react/likert/dist/index.js'
    )
);
registerController(
  'likert',
  () =>
    import(
      /* @vite-ignore */
      '/@fs/Users/eelco.hillenius/dev/prj/pie/pie-elements-ng/packages/elements-react/likert/dist/controller/index.js'
    )
);
registerAuthor(
  'likert',
  () =>
    import(
      /* @vite-ignore */
      '/@fs/Users/eelco.hillenius/dev/prj/pie/pie-elements-ng/packages/elements-react/likert/dist/author/index.js'
    )
);

// Register element: match
registerElement(
  'match',
  () =>
    import(
      /* @vite-ignore */
      '/@fs/Users/eelco.hillenius/dev/prj/pie/pie-elements-ng/packages/elements-react/match/dist/index.js'
    )
);
registerController(
  'match',
  () =>
    import(
      /* @vite-ignore */
      '/@fs/Users/eelco.hillenius/dev/prj/pie/pie-elements-ng/packages/elements-react/match/dist/controller/index.js'
    )
);
registerAuthor(
  'match',
  () =>
    import(
      /* @vite-ignore */
      '/@fs/Users/eelco.hillenius/dev/prj/pie/pie-elements-ng/packages/elements-react/match/dist/author/index.js'
    )
);

// Register element: match-list
registerElement(
  'match-list',
  () =>
    import(
      /* @vite-ignore */
      '/@fs/Users/eelco.hillenius/dev/prj/pie/pie-elements-ng/packages/elements-react/match-list/dist/index.js'
    )
);
registerController(
  'match-list',
  () =>
    import(
      /* @vite-ignore */
      '/@fs/Users/eelco.hillenius/dev/prj/pie/pie-elements-ng/packages/elements-react/match-list/dist/controller/index.js'
    )
);

// Register element: math-inline
registerElement(
  'math-inline',
  () =>
    import(
      /* @vite-ignore */
      '/@fs/Users/eelco.hillenius/dev/prj/pie/pie-elements-ng/packages/elements-react/math-inline/dist/index.js'
    )
);
registerController(
  'math-inline',
  () =>
    import(
      /* @vite-ignore */
      '/@fs/Users/eelco.hillenius/dev/prj/pie/pie-elements-ng/packages/elements-react/math-inline/dist/controller/index.js'
    )
);
registerAuthor(
  'math-inline',
  () =>
    import(
      /* @vite-ignore */
      '/@fs/Users/eelco.hillenius/dev/prj/pie/pie-elements-ng/packages/elements-react/math-inline/dist/author/index.js'
    )
);
registerPrint(
  'math-inline',
  () =>
    import(
      /* @vite-ignore */
      '/@fs/Users/eelco.hillenius/dev/prj/pie/pie-elements-ng/packages/elements-react/math-inline/dist/print/index.js'
    )
);

// Register element: math-templated
registerElement(
  'math-templated',
  () =>
    import(
      /* @vite-ignore */
      '/@fs/Users/eelco.hillenius/dev/prj/pie/pie-elements-ng/packages/elements-react/math-templated/dist/index.js'
    )
);
registerController(
  'math-templated',
  () =>
    import(
      /* @vite-ignore */
      '/@fs/Users/eelco.hillenius/dev/prj/pie/pie-elements-ng/packages/elements-react/math-templated/dist/controller/index.js'
    )
);
registerAuthor(
  'math-templated',
  () =>
    import(
      /* @vite-ignore */
      '/@fs/Users/eelco.hillenius/dev/prj/pie/pie-elements-ng/packages/elements-react/math-templated/dist/author/index.js'
    )
);
registerPrint(
  'math-templated',
  () =>
    import(
      /* @vite-ignore */
      '/@fs/Users/eelco.hillenius/dev/prj/pie/pie-elements-ng/packages/elements-react/math-templated/dist/print/index.js'
    )
);

// Register element: matrix
registerElement(
  'matrix',
  () =>
    import(
      /* @vite-ignore */
      '/@fs/Users/eelco.hillenius/dev/prj/pie/pie-elements-ng/packages/elements-react/matrix/dist/index.js'
    )
);
registerController(
  'matrix',
  () =>
    import(
      /* @vite-ignore */
      '/@fs/Users/eelco.hillenius/dev/prj/pie/pie-elements-ng/packages/elements-react/matrix/dist/controller/index.js'
    )
);
registerAuthor(
  'matrix',
  () =>
    import(
      /* @vite-ignore */
      '/@fs/Users/eelco.hillenius/dev/prj/pie/pie-elements-ng/packages/elements-react/matrix/dist/author/index.js'
    )
);

// Register element: multi-trait-rubric
registerElement(
  'multi-trait-rubric',
  () =>
    import(
      /* @vite-ignore */
      '/@fs/Users/eelco.hillenius/dev/prj/pie/pie-elements-ng/packages/elements-react/multi-trait-rubric/dist/index.js'
    )
);
registerController(
  'multi-trait-rubric',
  () =>
    import(
      /* @vite-ignore */
      '/@fs/Users/eelco.hillenius/dev/prj/pie/pie-elements-ng/packages/elements-react/multi-trait-rubric/dist/controller/index.js'
    )
);
registerAuthor(
  'multi-trait-rubric',
  () =>
    import(
      /* @vite-ignore */
      '/@fs/Users/eelco.hillenius/dev/prj/pie/pie-elements-ng/packages/elements-react/multi-trait-rubric/dist/author/index.js'
    )
);

// Register element: multiple-choice
registerElement(
  'multiple-choice',
  () =>
    import(
      /* @vite-ignore */
      '/@fs/Users/eelco.hillenius/dev/prj/pie/pie-elements-ng/packages/elements-react/multiple-choice/dist/index.js'
    )
);
registerController(
  'multiple-choice',
  () =>
    import(
      /* @vite-ignore */
      '/@fs/Users/eelco.hillenius/dev/prj/pie/pie-elements-ng/packages/elements-react/multiple-choice/dist/controller/index.js'
    )
);
registerAuthor(
  'multiple-choice',
  () =>
    import(
      /* @vite-ignore */
      '/@fs/Users/eelco.hillenius/dev/prj/pie/pie-elements-ng/packages/elements-react/multiple-choice/dist/author/index.js'
    )
);
registerPrint(
  'multiple-choice',
  () =>
    import(
      /* @vite-ignore */
      '/@fs/Users/eelco.hillenius/dev/prj/pie/pie-elements-ng/packages/elements-react/multiple-choice/dist/print/index.js'
    )
);

// Register element: number-line
registerElement(
  'number-line',
  () =>
    import(
      /* @vite-ignore */
      '/@fs/Users/eelco.hillenius/dev/prj/pie/pie-elements-ng/packages/elements-react/number-line/dist/index.js'
    )
);
registerController(
  'number-line',
  () =>
    import(
      /* @vite-ignore */
      '/@fs/Users/eelco.hillenius/dev/prj/pie/pie-elements-ng/packages/elements-react/number-line/dist/controller/index.js'
    )
);
registerAuthor(
  'number-line',
  () =>
    import(
      /* @vite-ignore */
      '/@fs/Users/eelco.hillenius/dev/prj/pie/pie-elements-ng/packages/elements-react/number-line/dist/author/index.js'
    )
);

// Register element: passage
registerElement(
  'passage',
  () =>
    import(
      /* @vite-ignore */
      '/@fs/Users/eelco.hillenius/dev/prj/pie/pie-elements-ng/packages/elements-react/passage/dist/index.js'
    )
);
registerController(
  'passage',
  () =>
    import(
      /* @vite-ignore */
      '/@fs/Users/eelco.hillenius/dev/prj/pie/pie-elements-ng/packages/elements-react/passage/dist/controller/index.js'
    )
);
registerAuthor(
  'passage',
  () =>
    import(
      /* @vite-ignore */
      '/@fs/Users/eelco.hillenius/dev/prj/pie/pie-elements-ng/packages/elements-react/passage/dist/author/index.js'
    )
);
registerPrint(
  'passage',
  () =>
    import(
      /* @vite-ignore */
      '/@fs/Users/eelco.hillenius/dev/prj/pie/pie-elements-ng/packages/elements-react/passage/dist/print/index.js'
    )
);

// Register element: placement-ordering
registerElement(
  'placement-ordering',
  () =>
    import(
      /* @vite-ignore */
      '/@fs/Users/eelco.hillenius/dev/prj/pie/pie-elements-ng/packages/elements-react/placement-ordering/dist/index.js'
    )
);
registerController(
  'placement-ordering',
  () =>
    import(
      /* @vite-ignore */
      '/@fs/Users/eelco.hillenius/dev/prj/pie/pie-elements-ng/packages/elements-react/placement-ordering/dist/controller/index.js'
    )
);
registerAuthor(
  'placement-ordering',
  () =>
    import(
      /* @vite-ignore */
      '/@fs/Users/eelco.hillenius/dev/prj/pie/pie-elements-ng/packages/elements-react/placement-ordering/dist/author/index.js'
    )
);

// Register element: rubric
registerElement(
  'rubric',
  () =>
    import(
      /* @vite-ignore */
      '/@fs/Users/eelco.hillenius/dev/prj/pie/pie-elements-ng/packages/elements-react/rubric/dist/index.js'
    )
);
registerController(
  'rubric',
  () =>
    import(
      /* @vite-ignore */
      '/@fs/Users/eelco.hillenius/dev/prj/pie/pie-elements-ng/packages/elements-react/rubric/dist/controller/index.js'
    )
);
registerAuthor(
  'rubric',
  () =>
    import(
      /* @vite-ignore */
      '/@fs/Users/eelco.hillenius/dev/prj/pie/pie-elements-ng/packages/elements-react/rubric/dist/author/index.js'
    )
);
registerPrint(
  'rubric',
  () =>
    import(
      /* @vite-ignore */
      '/@fs/Users/eelco.hillenius/dev/prj/pie/pie-elements-ng/packages/elements-react/rubric/dist/print/index.js'
    )
);

// Register element: select-text
registerElement(
  'select-text',
  () =>
    import(
      /* @vite-ignore */
      '/@fs/Users/eelco.hillenius/dev/prj/pie/pie-elements-ng/packages/elements-react/select-text/dist/index.js'
    )
);
registerController(
  'select-text',
  () =>
    import(
      /* @vite-ignore */
      '/@fs/Users/eelco.hillenius/dev/prj/pie/pie-elements-ng/packages/elements-react/select-text/dist/controller/index.js'
    )
);
registerAuthor(
  'select-text',
  () =>
    import(
      /* @vite-ignore */
      '/@fs/Users/eelco.hillenius/dev/prj/pie/pie-elements-ng/packages/elements-react/select-text/dist/author/index.js'
    )
);
registerPrint(
  'select-text',
  () =>
    import(
      /* @vite-ignore */
      '/@fs/Users/eelco.hillenius/dev/prj/pie/pie-elements-ng/packages/elements-react/select-text/dist/print/index.js'
    )
);

// Register element: simple-cloze
registerElement(
  'simple-cloze',
  () =>
    import(
      /* @vite-ignore */
      '/@fs/Users/eelco.hillenius/dev/prj/pie/pie-elements-ng/packages/elements-svelte/simple-cloze/dist/index.js'
    )
);
registerController(
  'simple-cloze',
  () =>
    import(
      /* @vite-ignore */
      '/@fs/Users/eelco.hillenius/dev/prj/pie/pie-elements-ng/packages/elements-svelte/simple-cloze/dist/controller/index.js'
    )
);
registerAuthor(
  'simple-cloze',
  () =>
    import(
      /* @vite-ignore */
      '/@fs/Users/eelco.hillenius/dev/prj/pie/pie-elements-ng/packages/elements-svelte/simple-cloze/dist/author/index.js'
    )
);
registerPrint(
  'simple-cloze',
  () =>
    import(
      /* @vite-ignore */
      '/@fs/Users/eelco.hillenius/dev/prj/pie/pie-elements-ng/packages/elements-svelte/simple-cloze/dist/print/index.js'
    )
);
