// @auto-generated by upstream:sync
// Local ESM replacement for config-ui's tiny mathjs fraction conversion usage.
type FractionLike = {
  d: number;
  n: number;
  s?: number;
};

const isFractionLike = (value: unknown): value is FractionLike =>
  typeof value === 'object' &&
  value !== null &&
  typeof (value as FractionLike).n === 'number' &&
  typeof (value as FractionLike).d === 'number';

export const fractionToNumber = (value: FractionLike | number | string): number => {
  if (typeof value === 'number') {
    return value;
  }

  if (isFractionLike(value)) {
    const sign = value.s ?? 1;
    return (sign * value.n) / value.d;
  }

  const normalized = String(value).trim();
  const fractionMatch = normalized.match(/^([+-]?\d+)\s*\/\s*([+-]?\d+)$/);
  if (fractionMatch) {
    const numerator = Number.parseInt(fractionMatch[1] ?? '0', 10);
    const denominator = Number.parseInt(fractionMatch[2] ?? '1', 10);
    return numerator / denominator;
  }

  return Number(normalized);
};
