/** Generated by vite.browser.config.ts from the installed MathJax packages. */
declare module 'virtual:bundled-mathjax-assets' {
  /** The CHTML font's woff2 files on jsDelivr, for the bundled font version. */
  export const FONT_URL: string;
  /** The woff2 files of the font extension mhchem draws its arrows with, on jsDelivr. */
  export const MHCHEM_FONT_URL: string;
  /** The speech worker and its rule files on jsDelivr, for the bundled MathJax version. */
  export const SRE_URL: string;
  /** Each dynamic range of the font, by file name, as a chunk of the build. */
  export const dynamicFonts: Record<string, () => Promise<unknown>>;
}
