/** Generated by vite.browser.config.ts from the installed MathJax font. */
declare module 'virtual:bundled-mathjax-assets' {
  /** Each dynamic range of the font, by file name, as a chunk of the build. */
  export const dynamicFonts: Record<string, () => Promise<unknown>>;
}
