// @ts-nocheck

export default {
  alternates: [],
  categories: [],
  categoriesPerRow: 2,
  choices: [],
  choicesLabel: '',
  choicesPosition: 'below',
  correctResponse: [],
  feedbackEnabled: false,
  lockChoiceOrder: true,
  maxAnswerChoices: 6,
  maxChoicesPerCategory: 0,
  partialScoring: true,
  prompt: '',
  promptEnabled: true,
  rationale: '',
  rationaleEnabled: true,
  rowLabels: [''],
  studentInstructionsEnabled: true,
  teacherInstructions: '',
  teacherInstructionsEnabled: true,
  toolbarEditorPosition: 'bottom',
  minRowHeight: '80px',
};
