// @ts-nocheck
/**
 * Element Static Imports
 *
 * AUTO-GENERATED by scripts/generate-element-imports.ts - DO NOT EDIT MANUALLY
 *
 * This file registers all available PIE elements using package specifiers.
 * We intentionally avoid absolute filesystem paths to keep local-machine
 * details out of generated files and build artifacts.
 *
 * IMPORTANT: import specifiers are static strings so Vite can analyze
 * and optimize them without leaking machine-specific absolute paths.
 *
 * The workspace resolver plugin handles resolving dependencies that the
 * element dist files import (like @pie-element/shared-math-rendering-katex)
 *
 * Generated at build-time by prebuild script
 */

// Element module registry
const elementModules = new Map();
const controllerModules = new Map();
const authorModules = new Map();
const printModules = new Map();

// Register helper functions
export function registerElement(name, importer) {
  elementModules.set(name, importer);
}

export function registerController(name, importer) {
  controllerModules.set(name, importer);
}

export function registerAuthor(name, importer) {
  authorModules.set(name, importer);
}

export function registerPrint(name, importer) {
  printModules.set(name, importer);
}

// Get helper functions
export function getElementModule(name) {
  return elementModules.get(name);
}

export function getControllerModule(name) {
  return controllerModules.get(name);
}

export function getAuthorModule(name) {
  return authorModules.get(name);
}

export function getPrintModule(name) {
  return printModules.get(name);
}

export function hasElementModule(name) {
  return elementModules.has(name);
}

// ============================================================================
// ELEMENT REGISTRATIONS
// ============================================================================

// Register element: categorize
registerElement('categorize', () => import('@pie-element/categorize/delivery'));
registerController('categorize', () => import('@pie-element/categorize/controller'));
registerAuthor('categorize', () => import('@pie-element/categorize/author'));

// Register element: charting
registerElement('charting', () => import('@pie-element/charting/delivery'));
registerController('charting', () => import('@pie-element/charting/controller'));
registerAuthor('charting', () => import('@pie-element/charting/author'));

// Register element: complex-rubric
registerElement('complex-rubric', () => import('@pie-element/complex-rubric/delivery'));
registerController('complex-rubric', () => import('@pie-element/complex-rubric/controller'));
registerAuthor('complex-rubric', () => import('@pie-element/complex-rubric/author'));
registerPrint('complex-rubric', () => import('@pie-element/complex-rubric/print'));

// Register element: drag-in-the-blank
registerElement('drag-in-the-blank', () => import('@pie-element/drag-in-the-blank/delivery'));
registerController('drag-in-the-blank', () => import('@pie-element/drag-in-the-blank/controller'));
registerAuthor('drag-in-the-blank', () => import('@pie-element/drag-in-the-blank/author'));

// Register element: drawing-response
registerElement('drawing-response', () => import('@pie-element/drawing-response/delivery'));
registerController('drawing-response', () => import('@pie-element/drawing-response/controller'));
registerAuthor('drawing-response', () => import('@pie-element/drawing-response/author'));

// Register element: ebsr
registerElement('ebsr', () => import('@pie-element/ebsr/delivery'));
registerController('ebsr', () => import('@pie-element/ebsr/controller'));
registerAuthor('ebsr', () => import('@pie-element/ebsr/author'));
registerPrint('ebsr', () => import('@pie-element/ebsr/print'));

// Register element: explicit-constructed-response
registerElement('explicit-constructed-response', () => import('@pie-element/explicit-constructed-response/delivery'));
registerController('explicit-constructed-response', () => import('@pie-element/explicit-constructed-response/controller'));
registerAuthor('explicit-constructed-response', () => import('@pie-element/explicit-constructed-response/author'));
registerPrint('explicit-constructed-response', () => import('@pie-element/explicit-constructed-response/print'));

// Register element: extended-text-entry
registerElement('extended-text-entry', () => import('@pie-element/extended-text-entry/delivery'));
registerController('extended-text-entry', () => import('@pie-element/extended-text-entry/controller'));
registerAuthor('extended-text-entry', () => import('@pie-element/extended-text-entry/author'));
registerPrint('extended-text-entry', () => import('@pie-element/extended-text-entry/print'));

// Register element: fraction-model
registerElement('fraction-model', () => import('@pie-element/fraction-model/delivery'));
registerController('fraction-model', () => import('@pie-element/fraction-model/controller'));
registerAuthor('fraction-model', () => import('@pie-element/fraction-model/author'));

// Register element: graphing
registerElement('graphing', () => import('@pie-element/graphing/delivery'));
registerController('graphing', () => import('@pie-element/graphing/controller'));
registerAuthor('graphing', () => import('@pie-element/graphing/author'));

// Register element: graphing-solution-set
registerElement('graphing-solution-set', () => import('@pie-element/graphing-solution-set/delivery'));
registerController('graphing-solution-set', () => import('@pie-element/graphing-solution-set/controller'));
registerAuthor('graphing-solution-set', () => import('@pie-element/graphing-solution-set/author'));

// Register element: hotspot
registerElement('hotspot', () => import('@pie-element/hotspot/delivery'));
registerController('hotspot', () => import('@pie-element/hotspot/controller'));
registerAuthor('hotspot', () => import('@pie-element/hotspot/author'));

// Register element: image-cloze-association
registerElement('image-cloze-association', () => import('@pie-element/image-cloze-association/delivery'));
registerController('image-cloze-association', () => import('@pie-element/image-cloze-association/controller'));
registerAuthor('image-cloze-association', () => import('@pie-element/image-cloze-association/author'));

// Register element: inline-dropdown
registerElement('inline-dropdown', () => import('@pie-element/inline-dropdown/delivery'));
registerController('inline-dropdown', () => import('@pie-element/inline-dropdown/controller'));
registerAuthor('inline-dropdown', () => import('@pie-element/inline-dropdown/author'));

// Register element: likert
registerElement('likert', () => import('@pie-element/likert/delivery'));
registerController('likert', () => import('@pie-element/likert/controller'));
registerAuthor('likert', () => import('@pie-element/likert/author'));

// Register element: match
registerElement('match', () => import('@pie-element/match/delivery'));
registerController('match', () => import('@pie-element/match/controller'));
registerAuthor('match', () => import('@pie-element/match/author'));

// Register element: match-list
registerElement('match-list', () => import('@pie-element/match-list/delivery'));
registerController('match-list', () => import('@pie-element/match-list/controller'));

// Register element: math-inline
registerElement('math-inline', () => import('@pie-element/math-inline/delivery'));
registerController('math-inline', () => import('@pie-element/math-inline/controller'));
registerAuthor('math-inline', () => import('@pie-element/math-inline/author'));
registerPrint('math-inline', () => import('@pie-element/math-inline/print'));

// Register element: math-templated
registerElement('math-templated', () => import('@pie-element/math-templated/delivery'));
registerController('math-templated', () => import('@pie-element/math-templated/controller'));
registerAuthor('math-templated', () => import('@pie-element/math-templated/author'));
registerPrint('math-templated', () => import('@pie-element/math-templated/print'));

// Register element: matrix
registerElement('matrix', () => import('@pie-element/matrix/delivery'));
registerController('matrix', () => import('@pie-element/matrix/controller'));
registerAuthor('matrix', () => import('@pie-element/matrix/author'));

// Register element: multi-trait-rubric
registerElement('multi-trait-rubric', () => import('@pie-element/multi-trait-rubric/delivery'));
registerController('multi-trait-rubric', () => import('@pie-element/multi-trait-rubric/controller'));
registerAuthor('multi-trait-rubric', () => import('@pie-element/multi-trait-rubric/author'));

// Register element: multiple-choice
registerElement('multiple-choice', () => import('@pie-element/multiple-choice/delivery'));
registerController('multiple-choice', () => import('@pie-element/multiple-choice/controller'));
registerAuthor('multiple-choice', () => import('@pie-element/multiple-choice/author'));
registerPrint('multiple-choice', () => import('@pie-element/multiple-choice/print'));

// Register element: number-line
registerElement('number-line', () => import('@pie-element/number-line/delivery'));
registerController('number-line', () => import('@pie-element/number-line/controller'));
registerAuthor('number-line', () => import('@pie-element/number-line/author'));

// Register element: passage
registerElement('passage', () => import('@pie-element/passage/delivery'));
registerController('passage', () => import('@pie-element/passage/controller'));
registerAuthor('passage', () => import('@pie-element/passage/author'));
registerPrint('passage', () => import('@pie-element/passage/print'));

// Register element: placement-ordering
registerElement('placement-ordering', () => import('@pie-element/placement-ordering/delivery'));
registerController('placement-ordering', () => import('@pie-element/placement-ordering/controller'));
registerAuthor('placement-ordering', () => import('@pie-element/placement-ordering/author'));

// Register element: rubric
registerElement('rubric', () => import('@pie-element/rubric/delivery'));
registerController('rubric', () => import('@pie-element/rubric/controller'));
registerAuthor('rubric', () => import('@pie-element/rubric/author'));
registerPrint('rubric', () => import('@pie-element/rubric/print'));

// Register element: select-text
registerElement('select-text', () => import('@pie-element/select-text/delivery'));
registerController('select-text', () => import('@pie-element/select-text/controller'));
registerAuthor('select-text', () => import('@pie-element/select-text/author'));
registerPrint('select-text', () => import('@pie-element/select-text/print'));

// Register element: simple-cloze
registerElement('simple-cloze', () => import('@pie-element/simple-cloze/delivery'));
registerController('simple-cloze', () => import('@pie-element/simple-cloze/controller'));
registerAuthor('simple-cloze', () => import('@pie-element/simple-cloze/author'));
registerPrint('simple-cloze', () => import('@pie-element/simple-cloze/print'));

// Register element: mc-populated-blank
registerElement('mc-populated-blank', () => import('@pie-element/mc-populated-blank/delivery'));
registerController('mc-populated-blank', () => import('@pie-element/mc-populated-blank/controller'));
registerAuthor('mc-populated-blank', () => import('@pie-element/mc-populated-blank/author'));
registerPrint('mc-populated-blank', () => import('@pie-element/mc-populated-blank/print'));

// Register element: video-stimulus
registerElement('video-stimulus', () => import('@pie-element/video-stimulus/delivery'));
registerController('video-stimulus', () => import('@pie-element/video-stimulus/controller'));
registerAuthor('video-stimulus', () => import('@pie-element/video-stimulus/author'));

// Register element: venn-classification
registerElement('venn-classification', () => import('@pie-element/venn-classification/delivery'));
registerController('venn-classification', () => import('@pie-element/venn-classification/controller'));
registerAuthor('venn-classification', () => import('@pie-element/venn-classification/author'));
