import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import type { Logger } from '../../utils/logger.js';

/**
 * Extension Loader Generator
 *
 * Generates the main extension loader that initializes MathQuill
 * with all patches and extensions in the correct order.
 */

export function generateExtensionLoader(mathquillPath: string, logger: Logger): void {
  const loaderPath = join(mathquillPath, 'src/extensions/index.ts');

  const content = `/**
 * MathQuill Extensions Loader
 *
 * Loads all extensions in the correct order:
 * 1. Desmos base (via npm package)
 * 2. Khan Academy patches
 * 3. Learnosity features
 * 4. PIE features
 *
 * Generated by: pie mathquill:migrate
 * Date: ${new Date().toISOString().split('T')[0]}
 *
 * DO NOT EDIT MANUALLY - Regenerate with: pie mathquill:migrate
 */

import MathQuill from 'mathquill';
import type { MathQuillInterface, MathFieldInterface } from 'mathquill';

// Import Desmos MathQuill CSS
import 'mathquill/build/mathquill.css';

// Khan Academy patches
import {
  applyMobileKeyboardFixes,
  applyI18nAriaSupport,
} from './khan/index.js';

// Learnosity features
import {
  addRecurringDecimal,
  addNotSymbols,
  applyEmptyMethod,
} from './learnosity/index.js';

// PIE features
import {
  addMatrixCommands,
  addLRNExponent,
} from './pie/index.js';

// Import PIE matrix styles
import './pie/styles.css';

/**
 * Initialize MathQuill with all extensions
 *
 * This creates a MathQuill instance (v3 interface) with:
 * - Desmos base (TypeScript, modern)
 * - Khan Academy mobile and accessibility patches
 * - Learnosity educational features
 * - PIE custom extensions
 *
 * @returns Initialized MathQuill interface
 */
export function initializeMathQuill(): MathQuillInterface {
  // Get MathQuill v3 interface (no jQuery in public API)
  const MQ = MathQuill.getInterface(3);

  // Apply Khan Academy patches
  applyMobileKeyboardFixes(MQ);
  applyI18nAriaSupport(MQ);

  // Add Learnosity features
  addRecurringDecimal(MQ);
  addNotSymbols(MQ);
  applyEmptyMethod(MQ);

  // Add PIE features
  addMatrixCommands(MQ);
  addLRNExponent(MQ);

  return MQ;
}

// Create and export initialized instance
const MQ = initializeMathQuill();

// Default export: initialized MathQuill
export default MQ;

// Named exports
export const getInterface = MathQuill.getInterface;
export const MathField = MQ.MathField;
export const StaticMath = MQ.StaticMath;

// Re-export types
export type {
  MathQuillInterface,
  MathFieldInterface,
  StaticMathInterface,
  MathFieldConfig,
} from 'mathquill';
`;

  writeFileSync(loaderPath, content);
  logger.success(`   ✓ Generated extension loader`);
}
