/**
 * MathQuill Extensions Loader
 *
 * Loads all extensions in the correct order:
 * 1. Desmos base (via npm package)
 * 2. Khan Academy patches
 * 3. Learnosity features
 * 4. PIE features
 *
 * Generated by: pie mathquill:migrate
 * Date: 2026-02-03
 *
 * DO NOT EDIT MANUALLY - Regenerate with: pie mathquill:migrate
 */

import './setup-jquery-global.js';

// Import MathQuill - this loads the UMD bundle which sets up window.MathQuill
import 'mathquill/build/mathquill.js';
import type { MathQuillInterface } from 'mathquill';

// Note: Consumers must import Desmos MathQuill CSS themselves:
// import 'mathquill/build/mathquill.css';

// Access the global MathQuill object that the UMD bundle creates
// Type is defined in types.ts
const MathQuill = window.MathQuill!;
const PIE_PATCH_FLAG = '__pieExtensionsApplied';
let initializedMQ: MathQuillInterface | null = null;

// Khan Academy patches
import {
  applyMobileKeyboardFixes,
  applyI18nAriaSupport,
} from './khan/index.js';

// Learnosity features
import {
  addRecurringDecimal,
  addNotSymbols,
  applyEmptyMethod,
} from './learnosity/index.js';

// PIE features
import {
  addMatrixCommands,
  addLRNExponent,
  applyForkBackports,
} from './pie/index.js';

// Import PIE matrix styles
import './pie/styles.css';

/**
 * Initialize MathQuill with all extensions
 *
 * This creates a MathQuill instance (v3 interface) with:
 * - Desmos base (TypeScript, modern)
 * - Khan Academy mobile and accessibility patches
 * - Learnosity educational features
 * - PIE custom extensions
 *
 * @returns Initialized MathQuill interface
 */
export function initializeMathQuill(): MathQuillInterface {
  if (initializedMQ) {
    return initializedMQ;
  }

  // Prefer v3 API when available, but gracefully fall back for older runtimes.
  const MQ = getSupportedInterface(MathQuill as any);
  const patchTarget = getPatchTarget(MathQuill as any, MQ as any);

  // Avoid patching internals repeatedly when the module graph is loaded more than once.
  if ((patchTarget as any)[PIE_PATCH_FLAG]) {
    initializedMQ = MQ as unknown as MathQuillInterface;
    return initializedMQ;
  }

  // Apply Khan Academy patches (use any since they access internals)
  applyMobileKeyboardFixes(patchTarget as any);
  applyI18nAriaSupport(patchTarget as any);

  // Add Learnosity features
  addRecurringDecimal(patchTarget as any);
  addNotSymbols(patchTarget as any);
  applyEmptyMethod(patchTarget as any);

  // Add PIE features
  applyForkBackports(patchTarget as any);
  addMatrixCommands(patchTarget as any);
  addLRNExponent(patchTarget as any);

  (patchTarget as any)[PIE_PATCH_FLAG] = true;
  initializedMQ = MQ as unknown as MathQuillInterface;
  return initializedMQ;
}

function getSupportedInterface(mathQuillGlobal: any): any {
  if (typeof mathQuillGlobal?.getInterface !== 'function') {
    return mathQuillGlobal;
  }

  for (const version of [3, 2, 1]) {
    try {
      return mathQuillGlobal.getInterface(version);
    } catch {
      // Try the next lower interface version.
    }
  }

  return mathQuillGlobal;
}

function getPatchTarget(mathQuillGlobal: any, mathQuillInterface: any): any {
  if (mathQuillInterface?.L) {
    return mathQuillInterface;
  }
  if (mathQuillGlobal?.L) {
    return mathQuillGlobal;
  }
  return mathQuillInterface;
}

// Create and export initialized instance (v3 API - no jQuery required)
const MQ = initializeMathQuill();

/**
 * PIE-specific MathQuill wrapper
 *
 * This provides a v3 interface without requiring consumers to manage jQuery globals.
 * All PIE elements should use this instead of calling getInterface() directly.
 *
 * Features:
 * - MathField: Create editable math fields
 * - StaticMath: Render static math
 * - registerEmbed: Register custom embedded elements
 * - All PIE extensions (matrices, recurring decimals, etc.)
 */
export default MQ;

// Named exports for convenience
export const MathField = MQ.MathField;
export const StaticMath = MQ.StaticMath;

// Re-export types
export type {
  MathQuillInterface,
  MathFieldInterface,
  StaticMathInterface,
  MathFieldConfig,
} from 'mathquill';
