/**
 * MathQuill Extensions Loader
 *
 * Loads all extensions in the correct order:
 * 1. Desmos base (via npm package)
 * 2. Khan Academy patches
 * 3. Learnosity features
 * 4. PIE features
 *
 * Generated by: pie mathquill:migrate
 * Date: 2026-02-03
 *
 * DO NOT EDIT MANUALLY - Regenerate with: pie mathquill:migrate
 */

// Import MathQuill - this loads the UMD bundle which sets up window.MathQuill
import 'mathquill/build/mathquill.js';
import type { MathQuillInterface } from 'mathquill';

// Note: Consumers must import Desmos MathQuill CSS themselves:
// import 'mathquill/build/mathquill.css';

// Access the global MathQuill object that the UMD bundle creates
// Type is defined in types.ts
const MathQuill = window.MathQuill!;

// Khan Academy patches
import {
  applyMobileKeyboardFixes,
  applyI18nAriaSupport,
} from './khan/index.js';

// Learnosity features
import {
  addRecurringDecimal,
  addNotSymbols,
  applyEmptyMethod,
} from './learnosity/index.js';

// PIE features
import {
  addMatrixCommands,
  addLRNExponent,
} from './pie/index.js';

// Import PIE matrix styles
import './pie/styles.css';

/**
 * Initialize MathQuill with all extensions
 *
 * This creates a MathQuill instance (v3 interface) with:
 * - Desmos base (TypeScript, modern)
 * - Khan Academy mobile and accessibility patches
 * - Learnosity educational features
 * - PIE custom extensions
 *
 * @returns Initialized MathQuill interface
 */
export function initializeMathQuill(): MathQuillInterface {
  // Get MathQuill v3 interface (no jQuery in public API)
  const MQ = MathQuill.getInterface(3);

  // Apply Khan Academy patches (use any since they access internals)
  applyMobileKeyboardFixes(MQ as any);
  applyI18nAriaSupport(MQ as any);

  // Add Learnosity features
  addRecurringDecimal(MQ as any);
  addNotSymbols(MQ as any);
  applyEmptyMethod(MQ as any);

  // Add PIE features
  addMatrixCommands(MQ as any);
  addLRNExponent(MQ as any);

  return MQ as unknown as MathQuillInterface;
}

// Create and export initialized instance (v3 API - no jQuery required)
const MQ = initializeMathQuill();

/**
 * PIE-specific MathQuill wrapper
 *
 * This provides a v3 interface without jQuery dependency.
 * All PIE elements should use this instead of calling getInterface() directly.
 *
 * Features:
 * - MathField: Create editable math fields
 * - StaticMath: Render static math
 * - registerEmbed: Register custom embedded elements
 * - All PIE extensions (matrices, recurring decimals, etc.)
 */
export default MQ;

// Named exports for convenience
export const MathField = MQ.MathField;
export const StaticMath = MQ.StaticMath;

// Re-export types
export type {
  MathQuillInterface,
  MathFieldInterface,
  StaticMathInterface,
  MathFieldConfig,
} from 'mathquill';
