/** Token authors must include exactly once in `template` (HTML). */
export const BLANK_TOKEN = '{{blank}}';
/** Baseline values tuned to match historical CQT visuals; override via model.layoutLimits. */
export const DEFAULT_LAYOUT_LIMITS = {
  blankStandaloneWidthRem: 7,
  blankWideWidthRem: 10,
  blankUnderlineWidthPx: 2,
  blankUnderlineWideWidthPx: 4,
  horizontalChoiceWidthPx: 170,
  horizontalChoiceWidthVw: 30,
  horizontalChoiceTileMinHeightRem: 11,
  horizontalChoiceContentMinHeightRem: 7.5,
  selectedImageMaxHeightRem: 4,
  choiceImageMaxHeightRem: 5,
  listenButtonSizePx: 128,
  stimulusMinColumnPx: 210,
  textMinColumnPx: 260,
  legendMaxChars: 120,
  choiceGroupGapRem: 0.5,
  choiceRowGapRem: 0.5,
  toggleButtonGapRem: 0.5,
  horizontalChoiceRadioTopMarginRem: 0.5,
  audioBlankTemplateMarginTopRem: 0.8,
  audioBlankTemplateMarginBottomRem: 1.8,
  stimulusGridColumnGapRem: 2,
  stimulusGridRowGapRem: 0.7,
  stimulusSentenceMarginTopRem: 0.2,
  stimulusChoicesMarginTopRem: 0.9,
  tokenGridColumnGapRem: 1.5,
  tokenGridRowGapRem: 0.8,
  tokenTemplateMarginTopRem: 0.6,
  tokenInlineTokenGapRem: 0.35,
  tokenChoicesMarginTopRem: 0.2,
  inlineGridColumnGapRem: 1.5,
  inlineGridRowGapRem: 0.65,
  inlineTemplateMarginTopRem: 0.45,
  inlineChoicesMarginTopRem: 0.25,
} as const;

export default {
  model: {
    id: '1',
    element: 'mc-populated-blank',
    prompt: '<p><strong>Demo prompt</strong></p>',
    promptEnabled: true,
    interactionMode: 'populate_blank' as const,
    layoutProfile: '',
    choiceLayout: '',
    layoutProfilePresets: {},
    layoutLimits: { ...DEFAULT_LAYOUT_LIMITS },
    audioButtonSkin: null,
    audioButtonSkinsByLocale: {},
    uiText: {
      answerChoices: 'Answer choices',
      selectedAnswerInSentence: 'Selected answer in sentence',
      showCorrectAnswer: 'Show correct answer',
      hideCorrectAnswer: 'Hide correct answer',
      clickToEnableAutoplay: 'Click to enable audio autoplay',
      audioResourceUnavailable: 'Audio is enabled but no playable audio URL is configured.',
      transcriptLabel: 'Transcript',
      listenLabelEn: 'Listen',
      listenLabelEs: 'Escuchar',
    },
    sentenceHtml: '',
    template: `<p>The answer is ${BLANK_TOKEN}.</p>`,
    choiceMode: 'text' as const,
    choices: [
      { id: 'c1', labelHtml: '<p>Option A</p>' },
      { id: 'c2', labelHtml: '<p>Option B</p>' },
      { id: 'c3', labelHtml: '<p>Option C</p>' },
    ],
    correctChoiceId: 'c2',
    hasAudio: false,
    autoplayAudioEnabled: false,
    completeAudioEnabled: false,
    audioUrl: '',
    audioTranscript: '',
    showVisibleTranscript: false,
    locale: '',
    teacherInstructions: '',
    teacherInstructionsEnabled: false,
  },
  configuration: {
    prompt: {
      label: 'Prompt',
      settings: true,
    },
  },
};
