export type LayoutLimits = {
  blankStandaloneWidthRem: number;
  blankWideWidthRem: number;
  blankUnderlineWidthPx: number;
  blankUnderlineWideWidthPx: number;
  horizontalChoiceWidthPx: number;
  horizontalChoiceWidthVw: number;
  horizontalChoiceTileMinHeightRem: number;
  horizontalChoiceContentMinHeightRem: number;
  selectedImageMaxHeightRem: number;
  choiceImageMaxHeightRem: number;
  listenButtonSizePx: number;
  stimulusMinColumnPx: number;
  textMinColumnPx: number;
  legendMaxChars: number;
  choiceGroupGapRem: number;
  choiceRowGapRem: number;
  toggleButtonGapRem: number;
  horizontalChoiceRadioTopMarginRem: number;
  audioBlankTemplateMarginTopRem: number;
  audioBlankTemplateMarginBottomRem: number;
  audioInstructionsMaxWidthPx: number;
  narrowHorizontalChoiceMaxWidthPx: number;
  stimulusGridColumnGapRem: number;
  stimulusGridRowGapRem: number;
  stimulusSentenceMarginTopRem: number;
  stimulusChoicesMarginTopRem: number;
  tokenGridColumnGapRem: number;
  tokenGridRowGapRem: number;
  tokenTemplateMarginTopRem: number;
  tokenInlineTokenGapRem: number;
  tokenChoicesMarginTopRem: number;
  inlineGridColumnGapRem: number;
  inlineGridRowGapRem: number;
  inlineTemplateMarginTopRem: number;
  inlineChoicesMarginTopRem: number;
};

/** Baseline values tuned to match historical CQT visuals; override via model.layoutLimits. */
export const DEFAULT_LAYOUT_LIMITS: LayoutLimits = {
  blankStandaloneWidthRem: 7,
  blankWideWidthRem: 10,
  blankUnderlineWidthPx: 2,
  blankUnderlineWideWidthPx: 4,
  horizontalChoiceWidthPx: 170,
  horizontalChoiceWidthVw: 30,
  horizontalChoiceTileMinHeightRem: 11,
  horizontalChoiceContentMinHeightRem: 7.5,
  selectedImageMaxHeightRem: 4,
  choiceImageMaxHeightRem: 5,
  listenButtonSizePx: 128,
  stimulusMinColumnPx: 210,
  textMinColumnPx: 260,
  legendMaxChars: 120,
  choiceGroupGapRem: 0.5,
  choiceRowGapRem: 0.5,
  toggleButtonGapRem: 0.5,
  horizontalChoiceRadioTopMarginRem: 0.5,
  audioBlankTemplateMarginTopRem: 0.8,
  audioBlankTemplateMarginBottomRem: 1.8,
  audioInstructionsMaxWidthPx: 875,
  narrowHorizontalChoiceMaxWidthPx: 230,
  stimulusGridColumnGapRem: 2,
  stimulusGridRowGapRem: 0.7,
  stimulusSentenceMarginTopRem: 0.2,
  stimulusChoicesMarginTopRem: 0.9,
  tokenGridColumnGapRem: 1.5,
  tokenGridRowGapRem: 0.8,
  tokenTemplateMarginTopRem: 0.6,
  tokenInlineTokenGapRem: 0.35,
  tokenChoicesMarginTopRem: 0.2,
  inlineGridColumnGapRem: 1.5,
  inlineGridRowGapRem: 0.65,
  inlineTemplateMarginTopRem: 0.45,
  inlineChoicesMarginTopRem: 0.25,
};
